/* Generated by python/scripts/generate_reader_apparatus_frontend_payloads.py. */
import type { ReaderApparatusResponse } from "@/lib/reader/apparatus";

import payload000 from "./arxiv-2606-source-package.json";
import payload001 from "./epub-gutenberg-waste-land-negative.json";
import payload002 from "./epub-standardebooks-eliot-poetry.json";
import payload003 from "./epub-standardebooks-eliot-poetry-advanced.json";
import payload004 from "./epub-standardebooks-james-pragmatism.json";
import payload005 from "./epub-standardebooks-james-pragmatism-advanced.json";
import payload006 from "./epub-synthetic-noteref.json";
import payload007 from "./html-distill-custom-citations.json";
import payload008 from "./html-distill-gp-full.json";
import payload009 from "./html-distill-growing-ca-full.json";
import payload010 from "./html-distill-legacy-bibtex.json";
import payload011 from "./html-distill-misread-tsne-full.json";
import payload012 from "./html-distill-research-debt-full.json";
import payload013 from "./html-gutenberg-argonautica-full.json";
import payload014 from "./html-gutenberg-notes-chapter-negative.json";
import payload015 from "./html-gutenberg-waste-land-full.json";
import payload016 from "./html-gwern-dpub-endnotes.json";
import payload017 from "./html-gwern-sidenote-full.json";
import payload018 from "./html-legacy-named-notes.json";
import payload019 from "./html-legacy-named-notes-negative.json";
import payload020 from "./html-mediawiki-references.json";
import payload021 from "./html-numinous-ttft-full.json";
import payload022 from "./html-tufte-css-full.json";
import payload023 from "./html-tufte-sidenote.json";
import payload024 from "./html-wikipedia-waste-land-full.json";
import payload025 from "./pdf-attention-native-link-graph.json";
import payload026 from "./pdf-commons-waste-land-negative.json";
import payload027 from "./pdf-law-review-footnotes.json";
import payload028 from "./pdf-philpapers-lop-aiz-unsupported.json";
import payload029 from "./tei-philpapers-lop-aiz-grobid-0-8-2.json";

export interface ReaderApparatusPayloadFixture {
  fixture_id: string;
  source_fixture_path: string;
  source_fixture_sha256: string;
  apparatus: ReaderApparatusResponse;
}

export interface ReaderApparatusFixtureEntry {
  fixtureId: string;
  payload: ReaderApparatusPayloadFixture;
  expectedReaderToolsSurface: "citations_tab_rows" | "citations_tab_omitted";
  expectedStatus: "ready" | "empty" | "partial" | "unsupported" | "failed";
  expectedItemCount: number;
  expectedEdgeCount: number;
  expectedRowCount: number;
  bodyNeedles: string[];
  surfaceContract: "reader_apparatus_empty_sidecar" | "reader_apparatus_sidecar_rows";
}

export const readerApparatusPayloadFixtures: ReaderApparatusFixtureEntry[] = [
  {
    fixtureId: "arxiv-2606-source-package",
    payload: payload000 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 33,
    expectedEdgeCount: 20,
    expectedRowCount: 16,
    bodyNeedles: ["Annotated References in the Historiography on Venice", "PDF-TEI Editor", "These authors contributed equally"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "epub-gutenberg-waste-land-negative",
    payload: payload001 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_omitted",
    expectedStatus: "empty",
    expectedItemCount: 0,
    expectedEdgeCount: 0,
    expectedRowCount: 0,
    bodyNeedles: [],
    surfaceContract: "reader_apparatus_empty_sidecar",
  },
  {
    fixtureId: "epub-standardebooks-eliot-poetry",
    payload: payload002 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 106,
    expectedEdgeCount: 53,
    expectedRowCount: 53,
    bodyNeedles: ["Aerated Bread Company", "The Peace which passeth understanding"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "epub-standardebooks-eliot-poetry-advanced",
    payload: payload003 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 106,
    expectedEdgeCount: 53,
    expectedRowCount: 53,
    bodyNeedles: ["Aerated Bread Company", "The Peace which passeth understanding"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "epub-standardebooks-james-pragmatism",
    payload: payload004 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 26,
    expectedEdgeCount: 13,
    expectedRowCount: 13,
    bodyNeedles: ["Morrison I. Swift", "Elements of Metaphysics"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "epub-standardebooks-james-pragmatism-advanced",
    payload: payload005 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 26,
    expectedEdgeCount: 13,
    expectedRowCount: 13,
    bodyNeedles: ["Morrison I. Swift", "Elements of Metaphysics"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "epub-synthetic-noteref",
    payload: payload006 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 2,
    expectedEdgeCount: 1,
    expectedRowCount: 1,
    bodyNeedles: ["EPUB note body for reader apparatus"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-distill-custom-citations",
    payload: payload007 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 4,
    expectedEdgeCount: 2,
    expectedRowCount: 2,
    bodyNeedles: ["Gaussian Processes in Machine Learning", "short explanatory note"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-distill-gp-full",
    payload: payload008 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 27,
    expectedEdgeCount: 15,
    expectedRowCount: 13,
    bodyNeedles: ["Gaussian Processes in Machine Learning", "Deep Neural Networks as Gaussian Processes"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-distill-growing-ca-full",
    payload: payload009 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 77,
    expectedEdgeCount: 44,
    expectedRowCount: 34,
    bodyNeedles: ["Top-down models in biology", "Self-regulatory feedback loops"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-distill-legacy-bibtex",
    payload: payload010 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 2,
    expectedEdgeCount: 1,
    expectedRowCount: 1,
    bodyNeedles: ["Visualizing data using t-SNE", "Journal of Machine Learning Research"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-distill-misread-tsne-full",
    payload: payload011 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 2,
    expectedEdgeCount: 1,
    expectedRowCount: 1,
    bodyNeedles: ["Visualizing data using t-SNE", "Journal of Machine Learning Research"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-distill-research-debt-full",
    payload: payload012 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 51,
    expectedEdgeCount: 29,
    expectedRowCount: 22,
    bodyNeedles: ["The Mythical Man-Month", "Visual Complex Analysis"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-gutenberg-argonautica-full",
    payload: payload013 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 78,
    expectedEdgeCount: 39,
    expectedRowCount: 39,
    bodyNeedles: ["Naucratis", "Anth. Pal.", "isle of Revealing"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-gutenberg-notes-chapter-negative",
    payload: payload014 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_omitted",
    expectedStatus: "empty",
    expectedItemCount: 0,
    expectedEdgeCount: 0,
    expectedRowCount: 0,
    bodyNeedles: [],
    surfaceContract: "reader_apparatus_empty_sidecar",
  },
  {
    fixtureId: "html-gutenberg-waste-land-full",
    payload: payload015 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_omitted",
    expectedStatus: "empty",
    expectedItemCount: 0,
    expectedEdgeCount: 0,
    expectedRowCount: 0,
    bodyNeedles: [],
    surfaceContract: "reader_apparatus_empty_sidecar",
  },
  {
    fixtureId: "html-gwern-dpub-endnotes",
    payload: payload016 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 2,
    expectedEdgeCount: 1,
    expectedRowCount: 1,
    bodyNeedles: ["source-authored note with a backlink"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-gwern-sidenote-full",
    payload: payload017 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 12,
    expectedEdgeCount: 6,
    expectedRowCount: 6,
    bodyNeedles: ["vertical pixels", "sidenotesplus"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-legacy-named-notes",
    payload: payload018 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 4,
    expectedEdgeCount: 2,
    expectedRowCount: 2,
    bodyNeedles: ["First source-authored legacy note body", "Second source-authored legacy note body"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-legacy-named-notes-negative",
    payload: payload019 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_omitted",
    expectedStatus: "empty",
    expectedItemCount: 0,
    expectedEdgeCount: 0,
    expectedRowCount: 0,
    bodyNeedles: [],
    surfaceContract: "reader_apparatus_empty_sidecar",
  },
  {
    fixtureId: "html-mediawiki-references",
    payload: payload020 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 2,
    expectedEdgeCount: 1,
    expectedRowCount: 1,
    bodyNeedles: ["discrepancy between line numbers"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-numinous-ttft-full",
    payload: payload021 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 40,
    expectedEdgeCount: 0,
    expectedRowCount: 40,
    bodyNeedles: ["Douglas Engelbart, Augmenting Human Intellect", "Why books don\u2019t work"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-tufte-css-full",
    payload: payload022 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 14,
    expectedEdgeCount: 7,
    expectedRowCount: 7,
    bodyNeedles: ["Beautiful Evidence", "This is a margin note. Notice there isn\u2019t a number preceding the note.", "Blue text, while also a widely recognizable clickable-text indicator"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-tufte-sidenote",
    payload: payload023 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 2,
    expectedEdgeCount: 1,
    expectedRowCount: 1,
    bodyNeedles: ["source-authored Tufte sidenote"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "html-wikipedia-waste-land-full",
    payload: payload024 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 714,
    expectedEdgeCount: 439,
    expectedRowCount: 445,
    bodyNeedles: ["Ackroyd 1984", "Eliot 1961"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "pdf-attention-native-link-graph",
    payload: payload025 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 116,
    expectedEdgeCount: 76,
    expectedRowCount: 76,
    bodyNeedles: ["Long short-term memory", "Neural machine translation by jointly learning to align and translate"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "pdf-commons-waste-land-negative",
    payload: payload026 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_omitted",
    expectedStatus: "empty",
    expectedItemCount: 0,
    expectedEdgeCount: 0,
    expectedRowCount: 0,
    bodyNeedles: ["THE WASTE LAND", "I. THE BURIAL OF THE DEAD", "NOT only the title", "Datta, dayadfivam, damyata", "Shantih"],
    surfaceContract: "reader_apparatus_empty_sidecar",
  },
  {
    fixtureId: "pdf-law-review-footnotes",
    payload: payload027 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "ready",
    expectedItemCount: 20,
    expectedEdgeCount: 10,
    expectedRowCount: 10,
    bodyNeedles: ["First legal footnote body", "continues on the following line", "Tenth legal footnote body verifies two-digit labels"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
  {
    fixtureId: "pdf-philpapers-lop-aiz-unsupported",
    payload: payload028 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_omitted",
    expectedStatus: "empty",
    expectedItemCount: 0,
    expectedEdgeCount: 0,
    expectedRowCount: 0,
    bodyNeedles: ["CC BY", "Endnotes", "References"],
    surfaceContract: "reader_apparatus_empty_sidecar",
  },
  {
    fixtureId: "tei-philpapers-lop-aiz-grobid-0-8-2",
    payload: payload029 as ReaderApparatusPayloadFixture,
    expectedReaderToolsSurface: "citations_tab_rows",
    expectedStatus: "partial",
    expectedItemCount: 250,
    expectedEdgeCount: 147,
    expectedRowCount: 174,
    bodyNeedles: ["ADective Economies", "Emotional Imperialism", "anger, aDective injustice"],
    surfaceContract: "reader_apparatus_sidecar_rows",
  },
];

export const readerApparatusRowPayloadFixtures = readerApparatusPayloadFixtures.filter(
  (entry) => entry.expectedReaderToolsSurface === "citations_tab_rows",
);

export const readerApparatusOmittedSurfacePayloadFixtures =
  readerApparatusPayloadFixtures.filter(
    (entry) => entry.expectedReaderToolsSurface === "citations_tab_omitted",
  );
