"""Remove chat retrieval DB cascades.

Revision ID: 0093
Revises: 0092_artifact_part_sources
Create Date: 2026-05-15
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0093"
down_revision: str | None = "0092_artifact_part_sources"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint(
        "chat_run_events_run_id_fkey",
        "chat_run_events",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_snapshot_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_assistant_message_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_conversation_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_chat_run_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_assistant_message_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_user_message_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_conversation_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_owner_user_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_retrievals_media_id_fkey",
        "message_retrievals",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_retrievals_tool_call_id_fkey",
        "message_retrievals",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_calls_assistant_message_id_fkey",
        "message_tool_calls",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_calls_user_message_id_fkey",
        "message_tool_calls",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_calls_conversation_id_fkey",
        "message_tool_calls",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "message_tool_calls_conversation_id_fkey",
        "message_tool_calls",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.create_foreign_key(
        "message_tool_calls_user_message_id_fkey",
        "message_tool_calls",
        "messages",
        ["user_message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "message_tool_calls_assistant_message_id_fkey",
        "message_tool_calls",
        "messages",
        ["assistant_message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "message_retrievals_tool_call_id_fkey",
        "message_retrievals",
        "message_tool_calls",
        ["tool_call_id"],
        ["id"],
    )
    op.create_foreign_key(
        "message_retrievals_media_id_fkey",
        "message_retrievals",
        "media",
        ["media_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_runs_owner_user_id_fkey",
        "chat_runs",
        "users",
        ["owner_user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_runs_conversation_id_fkey",
        "chat_runs",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_runs_user_message_id_fkey",
        "chat_runs",
        "messages",
        ["user_message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_runs_assistant_message_id_fkey",
        "chat_runs",
        "messages",
        ["assistant_message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_chat_run_id_fkey",
        "chat_prompt_assemblies",
        "chat_runs",
        ["chat_run_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_conversation_id_fkey",
        "chat_prompt_assemblies",
        "conversations",
        ["conversation_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_assistant_message_id_fkey",
        "chat_prompt_assemblies",
        "messages",
        ["assistant_message_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_snapshot_id_fkey",
        "chat_prompt_assemblies",
        "conversation_state_snapshots",
        ["snapshot_id"],
        ["id"],
    )
    op.create_foreign_key(
        "chat_run_events_run_id_fkey",
        "chat_run_events",
        "chat_runs",
        ["run_id"],
        ["id"],
    )


def downgrade() -> None:
    op.drop_constraint(
        "chat_run_events_run_id_fkey",
        "chat_run_events",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_snapshot_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_assistant_message_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_conversation_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_prompt_assemblies_chat_run_id_fkey",
        "chat_prompt_assemblies",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_assistant_message_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_user_message_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_conversation_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "chat_runs_owner_user_id_fkey",
        "chat_runs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_retrievals_media_id_fkey",
        "message_retrievals",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_retrievals_tool_call_id_fkey",
        "message_retrievals",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_calls_assistant_message_id_fkey",
        "message_tool_calls",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_calls_user_message_id_fkey",
        "message_tool_calls",
        type_="foreignkey",
    )
    op.drop_constraint(
        "message_tool_calls_conversation_id_fkey",
        "message_tool_calls",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "message_tool_calls_conversation_id_fkey",
        "message_tool_calls",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "message_tool_calls_user_message_id_fkey",
        "message_tool_calls",
        "messages",
        ["user_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "message_tool_calls_assistant_message_id_fkey",
        "message_tool_calls",
        "messages",
        ["assistant_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "message_retrievals_tool_call_id_fkey",
        "message_retrievals",
        "message_tool_calls",
        ["tool_call_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "message_retrievals_media_id_fkey",
        "message_retrievals",
        "media",
        ["media_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "chat_runs_owner_user_id_fkey",
        "chat_runs",
        "users",
        ["owner_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_runs_conversation_id_fkey",
        "chat_runs",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_runs_user_message_id_fkey",
        "chat_runs",
        "messages",
        ["user_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_runs_assistant_message_id_fkey",
        "chat_runs",
        "messages",
        ["assistant_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_chat_run_id_fkey",
        "chat_prompt_assemblies",
        "chat_runs",
        ["chat_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_conversation_id_fkey",
        "chat_prompt_assemblies",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_assistant_message_id_fkey",
        "chat_prompt_assemblies",
        "messages",
        ["assistant_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "chat_prompt_assemblies_snapshot_id_fkey",
        "chat_prompt_assemblies",
        "conversation_state_snapshots",
        ["snapshot_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "chat_run_events_run_id_fkey",
        "chat_run_events",
        "chat_runs",
        ["run_id"],
        ["id"],
        ondelete="CASCADE",
    )
