# Nexus Development Makefile
# Run `make help` for available commands

.PHONY: help setup dev down test test-back test-front test-migrations test-supabase test-back-no-services test-migrations-no-services test-supabase-no-services test-back-and-migrations test-back-network test-back-network-no-services test-back-real test-back-real-no-services ensure-services ensure-node-ingest ensure-e2e-deps lint lint-back lint-front fmt fmt-back fmt-front fmt-check typecheck build clean api web worker migrate migrate-test migrate-down seed verify verify-fast test-back-unit test-front-unit test-front-browser test-e2e test-e2e-ui _verify-fast-static _verify-fast-tests _verify-tests logs

# Load .env file if it exists (created by setup)
-include .env
# Load runtime ports if services are running (overrides .env)
-include .dev-ports
export

# Supabase local database port (fixed by supabase/config.toml)
SUPABASE_DB_PORT ?= 54322
SUPABASE_URL ?= http://127.0.0.1:54321
AUTH_ALLOWED_REDIRECT_ORIGINS ?= http://localhost:3000,http://localhost:3001

# Database URLs using Supabase local Postgres
DATABASE_URL ?= postgresql+psycopg://postgres:postgres@localhost:$(SUPABASE_DB_PORT)/postgres
DATABASE_URL_TEST ?= postgresql+psycopg://postgres:postgres@localhost:$(SUPABASE_DB_PORT)/nexus_test
DATABASE_URL_TEST_MIGRATIONS ?= postgresql+psycopg://postgres:postgres@localhost:$(SUPABASE_DB_PORT)/nexus_test_migrations

# Web port
WEB_PORT ?= 3000
# API port
API_PORT ?= 8000

help:
	@echo "Nexus Development Commands"
	@echo ""
	@echo "Setup:"
	@echo "  make setup          - Full project setup (deps + services + migrations)"
	@echo "  make dev            - Start development services (supabase)"
	@echo "  make down           - Stop development services"
	@echo "  make logs           - Show supabase logs"
	@echo "  make clean          - Clean generated files"
	@echo ""
	@echo "Test:"
	@echo "  make test           - Run all tests (backend + frontend)"
	@echo "  make test-back      - Run backend tests (excludes migrations)"
	@echo "  make test-back-network - Run backend tests requiring internet"
	@echo "  make test-back-real - Run real-content backend extraction tests"
	@echo "  make test-front     - Run frontend tests"
	@echo "  make test-migrations - Run migration tests (separate database)"
	@echo "  make test-supabase  - Run Supabase auth/storage integration tests"
	@echo ""
	@echo "Lint:"
	@echo "  make lint           - Run all linters (backend + frontend)"
	@echo "  make lint-back      - Run backend linter"
	@echo "  make lint-front     - Run frontend linter"
	@echo ""
	@echo "Format:"
	@echo "  make fmt            - Format all code (backend + frontend)"
	@echo "  make fmt-back       - Format backend code"
	@echo "  make fmt-front      - Fix frontend lint issues"
	@echo ""
	@echo "Run:"
	@echo "  make api            - Start API server (port 8000)"
	@echo "  make web            - Start web frontend (port 3000)"
	@echo "  make worker         - Start Postgres queue worker"
	@echo ""
	@echo "Database:"
	@echo "  make migrate        - Run migrations (dev database)"
	@echo "  make migrate-test   - Run migrations (test database)"
	@echo "  make migrate-down   - Rollback one migration"
	@echo "  make seed           - Seed development data"
	@echo ""
	@echo "Verify:"
	@echo "  make verify         - Full local verification (static + build + tests, no E2E)"
	@echo "  make verify-fast    - Fast feedback (static + unit tests only)"
	@echo ""
	@echo "Layer targets:"
	@echo "  make test-back-unit     - Backend unit tests only (no DB)"
	@echo "  make test-front-unit    - Frontend unit tests (Node)"
	@echo "  make test-front-browser - Frontend component tests (Vitest Browser Mode)"
	@echo "  make test-e2e           - Playwright E2E tests"
	@echo "  make test-e2e-ui        - Playwright E2E in UI mode"
	@echo ""
	@echo "Configuration (via environment or .env file):"
	@echo "  WEB_PORT            - Web frontend port (default: 3000)"
	@echo "  API_PORT            - API server port (default: 8000)"
	@echo ""

# === Setup ===

setup:
	./scripts/agency_setup.sh

dev:
	@echo "Starting Supabase local..."
	@supabase start || true
	@echo "# Runtime ports (auto-generated by make dev)" > .dev-ports
	@echo "Services started. Supabase DB: localhost:$(SUPABASE_DB_PORT)"

down:
	@echo "Stopping Supabase local..."
	@supabase stop || true
	@rm -f .dev-ports

logs:
	supabase logs

clean:
	./scripts/agency_archive.sh

# === Test ===

# Ensure services are running before tests that need them
ensure-services:
	@if ! docker ps --format '{{.Names}}' | grep -q '^supabase_db_'; then \
		echo "Services not running. Starting with 'make dev'..."; \
		$(MAKE) dev; \
	fi

# Ensure Node.js ingest worker dependencies are installed (jsdom + Readability)
ensure-node-ingest:
	@if [ ! -d "node/ingest/node_modules" ]; then \
		echo "Installing Node.js ingest worker dependencies..."; \
		cd node/ingest && npm ci; \
	fi

# Ensure E2E dependencies are installed
ensure-e2e-deps:
	@if [ ! -d "e2e/node_modules" ]; then \
		echo "Installing E2E dependencies..."; \
		cd e2e && npm install; \
	fi

test: test-back-and-migrations test-front

test-back-and-migrations:
	./scripts/with_test_services.sh $(MAKE) test-back-no-services test-migrations-no-services

test-back:
	./scripts/with_test_services.sh $(MAKE) test-back-no-services

test-back-no-services:
	$(MAKE) migrate-test
	$(MAKE) ensure-node-ingest
	cd python && NEXUS_ENV=test uv run pytest -v --ignore=tests/test_migrations.py

test-back-network:
	./scripts/with_test_services.sh $(MAKE) test-back-network-no-services

test-back-network-no-services:
	$(MAKE) migrate-test
	$(MAKE) ensure-node-ingest
	cd python && NEXUS_ENV=test uv run pytest -v --tb=short -m network -o addopts=""

test-back-real:
	./scripts/with_test_services.sh $(MAKE) test-back-real-no-services

test-back-real-no-services:
	$(MAKE) migrate-test
	$(MAKE) ensure-node-ingest
	cd python && NEXUS_ENV=test uv run pytest -v --tb=short -m slow -o addopts=""

test-front:
	cd apps/web && npm test -- --passWithNoTests

test-migrations:
	./scripts/with_test_services.sh $(MAKE) test-migrations-no-services

test-migrations-no-services:
	cd python && DATABASE_URL=$(DATABASE_URL_TEST_MIGRATIONS) NEXUS_ENV=test uv run pytest -v tests/test_migrations.py

test-supabase:
	./scripts/with_supabase_services.sh ./scripts/with_test_services.sh $(MAKE) test-supabase-no-services

test-supabase-no-services:
	$(MAKE) migrate-test
	cd python && NEXUS_ENV=test uv run pytest -v --tb=short -m supabase -o addopts=""

# === Lint ===

lint: lint-back lint-front

lint-back:
	cd python && uv run ruff check .

lint-front:
	cd apps/web && npm run lint

# === Format ===

fmt: fmt-back fmt-front

fmt-back:
	cd python && uv run ruff format .

fmt-front:
	cd apps/web && npm run lint -- --fix

# === Run ===

api:
	cd apps/api && PYTHONPATH=$$PWD/../../python DATABASE_URL=$(DATABASE_URL) \
		uv run --project ../../python uvicorn main:app --reload --port $(API_PORT)

web:
	cd apps/web && \
		FASTAPI_BASE_URL=http://localhost:$(API_PORT) \
		NEXUS_ENV=$${NEXUS_ENV:-local} \
		NEXT_PUBLIC_SUPABASE_URL=$${NEXT_PUBLIC_SUPABASE_URL:-$(SUPABASE_URL)} \
		NEXT_PUBLIC_SUPABASE_ANON_KEY=$${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$(SUPABASE_ANON_KEY)} \
		AUTH_ALLOWED_REDIRECT_ORIGINS=$${AUTH_ALLOWED_REDIRECT_ORIGINS:-$(AUTH_ALLOWED_REDIRECT_ORIGINS)} \
		npm run dev

worker:
	cd python && PYTHONPATH=$$PWD:$$PWD/.. \
		DATABASE_URL=$(DATABASE_URL) \
		uv run python -m apps.worker.main

# === Database ===

migrate:
	cd migrations && DATABASE_URL=$(DATABASE_URL) \
		uv run --project ../python alembic upgrade head

migrate-test:
	cd migrations && DATABASE_URL=$(DATABASE_URL_TEST) \
		uv run --project ../python alembic upgrade head

migrate-down:
	cd migrations && DATABASE_URL=$(DATABASE_URL) \
		uv run --project ../python alembic downgrade -1

seed:
	cd python && DATABASE_URL=$(DATABASE_URL) \
		SUPABASE_URL=$(SUPABASE_URL) \
		SUPABASE_SERVICE_KEY=$(SUPABASE_SERVICE_KEY) \
		uv run python ../scripts/seed_dev.py

# === Layer Targets ===

test-back-unit:
	cd python && NEXUS_ENV=test uv run pytest -v -m "unit and not integration"

test-front-unit:
	cd apps/web && npx vitest run --project unit

test-front-browser:
	@npx playwright install chromium >/dev/null 2>&1 || npx playwright install chromium
	cd apps/web && npx vitest run --project browser

test-e2e: ensure-e2e-deps
	@API_PORT=$$(./scripts/find_port.sh $(API_PORT) api) && \
	WEB_PORT=$$(./scripts/find_port.sh $(WEB_PORT) web) && \
	echo "Running e2e with API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT" && \
	cd e2e && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT npx playwright install --with-deps chromium && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT npx playwright test

test-e2e-ui: ensure-e2e-deps
	@API_PORT=$$(./scripts/find_port.sh $(API_PORT) api) && \
	WEB_PORT=$$(./scripts/find_port.sh $(WEB_PORT) web) && \
	echo "Running e2e ui with API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT" && \
	cd e2e && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT npx playwright install --with-deps chromium && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT npx playwright test --ui

# === Verify ===

# Helper targets for parallel execution within verify-fast
_verify-fast-static: lint fmt-check typecheck

_verify-fast-tests: test-back-unit test-front-unit

# Run with `make -j verify-fast` for parallel static + test execution.
# Sequential by default for deterministic output.
verify-fast: _verify-fast-static _verify-fast-tests
	@echo "=== verify-fast passed ==="

# Helper for parallel test execution within verify
_verify-tests: test-back-and-migrations test-front-unit test-front-browser

verify: lint fmt-check typecheck build _verify-tests
	@echo "=== All verification checks passed ==="

fmt-check:
	@echo "=== Checking Backend Formatting ==="
	cd python && uv run ruff format --check .
	@echo "✓ Backend formatting OK"

typecheck:
	@echo "=== Running Frontend Type Check ==="
	cd apps/web && npm run typecheck
	@echo "✓ Frontend type check OK"

build:
	@echo "=== Running Frontend Build ==="
	cd apps/web && npm run build
	@echo "✓ Frontend build OK"
