# Nexus Development Makefile
# Run `make help` for available commands.

.PHONY: help setup dev down logs clean api web worker migrate migrate-test migrate-down seed seed-real-media-e2e \
	check check-back type-back check-front check-workflows format format-back fix-front build audit \
	test-unit test test-back-unit test-back-integration test-front-unit test-front-browser \
	test-migrations test-supabase test-real-media test-live-providers test-e2e test-e2e-ui \
	verify verify-full \
	_ensure-node-ingest _ensure-e2e-deps _test-back-db-ready \
	_test-back-integration-raw _test-migrations-raw \
	_test-supabase-raw _test-real-media-backend-raw _test-live-providers-raw \
	_seed-real-media-e2e-raw _test-e2e-raw _test-real-media-e2e-raw _test-e2e-ui-raw

-include .env
-include .dev-ports
export

SUPABASE_DB_PORT ?= 54322
SUPABASE_URL ?= http://127.0.0.1:54321
AUTH_ALLOWED_REDIRECT_ORIGINS ?= http://localhost:3000,http://localhost:3001
STREAM_BASE_URL ?= http://localhost:$(API_PORT)
STREAM_CORS_ORIGINS ?= http://localhost:$(WEB_PORT),http://localhost:3000,http://localhost:3001

DATABASE_URL ?= postgresql+psycopg://postgres:postgres@localhost:$(SUPABASE_DB_PORT)/postgres
DATABASE_URL_TEST ?= postgresql+psycopg://postgres:postgres@localhost:$(SUPABASE_DB_PORT)/nexus_test
DATABASE_URL_TEST_MIGRATIONS ?= postgresql+psycopg://postgres:postgres@localhost:$(SUPABASE_DB_PORT)/nexus_test_migrations

WEB_PORT ?= 3000
API_PORT ?= 8000
PLAYWRIGHT_ARGS ?=

help:
	@echo "Nexus Development Commands"
	@echo ""
	@echo "Setup and run:"
	@echo "  make setup              - Install deps, start local services, run migrations"
	@echo "  make dev                - Start Supabase local services"
	@echo "  make down               - Stop Supabase local services"
	@echo "  make api                - Start FastAPI on API_PORT (default 8000)"
	@echo "  make web                - Start Next.js on WEB_PORT (default 3000)"
	@echo "  make worker             - Start the Postgres queue worker"
	@echo ""
	@echo "Routine gates:"
	@echo "  make check              - Static checks only"
	@echo "  make audit              - Dependency vulnerability audits"
	@echo "  make test-unit          - Fast backend and frontend unit tests"
	@echo "  make test               - All non-E2E automated tests"
	@echo "  make test-e2e           - Default Playwright E2E tests"
	@echo "  make test-real-media    - Strict deterministic real-media backend + Playwright gates"
	@echo "  make test-live-providers  - Strict live-provider backend gate"
	@echo "  make verify             - check + build + test"
	@echo "  make verify-full        - verify + real-media + live-provider + default E2E gates"
	@echo ""
	@echo "Focused targets:"
	@echo "  make type-back             - Backend type checking"
	@echo "  make check-workflows       - GitHub Actions lint/security checks"
	@echo "  make test-back-unit        - Backend unit tests only"
	@echo "  make test-back-integration - Backend DB/API integration tests"
	@echo "  make test-front-unit       - Frontend unit tests"
	@echo "  make test-front-browser    - Frontend browser component tests"
	@echo "  make test-migrations       - Alembic migration tests"
	@echo "  make test-supabase         - Supabase auth/storage integration tests"
	@echo "  make test-e2e-ui           - Playwright E2E in UI mode"
	@echo ""
	@echo "Formatting:"
	@echo "  make format             - Apply backend formatting and frontend lint fixes"
	@echo "  make format-back        - Format backend Python"
	@echo "  make fix-front          - Apply frontend ESLint fixes"
	@echo ""
	@echo "Database:"
	@echo "  make migrate            - Run migrations on the dev database"
	@echo "  make migrate-test       - Run migrations on the test database"
	@echo "  make migrate-down       - Roll back one dev migration"
	@echo "  make seed               - Seed development data"
	@echo "  make seed-real-media-e2e - Seed real-media E2E corpus through product paths"
	@echo ""
	@echo "Maintenance:"
	@echo "  make logs               - Show Supabase logs"
	@echo "  make clean              - Clean generated files"

setup:
	./scripts/agency_setup.sh

dev:
	@echo "Starting Supabase local..."
	@supabase start || true
	@echo "# Runtime ports (auto-generated by make dev)" > .dev-ports
	@echo "Services started. Supabase DB: localhost:$(SUPABASE_DB_PORT)"

down:
	@echo "Stopping Supabase local..."
	@supabase stop || true
	@rm -f .dev-ports

logs:
	supabase logs

clean:
	./scripts/agency_archive.sh

api:
	cd apps/api && PYTHONPATH=$$PWD/../../python DATABASE_URL=$(DATABASE_URL) \
		STREAM_BASE_URL=$(STREAM_BASE_URL) \
		STREAM_CORS_ORIGINS=$(STREAM_CORS_ORIGINS) \
		uv run --project ../../python uvicorn main:app --reload --port $(API_PORT)

web:
	cd apps/web && \
		FASTAPI_BASE_URL=http://localhost:$(API_PORT) \
		NEXUS_ENV=$${NEXUS_ENV:-local} \
		NEXT_PUBLIC_SUPABASE_URL=$${NEXT_PUBLIC_SUPABASE_URL:-$(SUPABASE_URL)} \
		NEXT_PUBLIC_SUPABASE_ANON_KEY=$${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$(SUPABASE_ANON_KEY)} \
		AUTH_ALLOWED_REDIRECT_ORIGINS=$${AUTH_ALLOWED_REDIRECT_ORIGINS:-$(AUTH_ALLOWED_REDIRECT_ORIGINS)} \
		bun run dev

worker:
	cd python && PYTHONPATH=$$PWD:$$PWD/.. DATABASE_URL=$(DATABASE_URL) \
		uv run python -m apps.worker.main

migrate:
	cd migrations && DATABASE_URL=$(DATABASE_URL) \
		uv run --project ../python alembic upgrade head

migrate-test:
	cd migrations && DATABASE_URL=$(DATABASE_URL_TEST) \
		uv run --project ../python alembic upgrade head

migrate-down:
	cd migrations && DATABASE_URL=$(DATABASE_URL) \
		uv run --project ../python alembic downgrade -1

seed:
	cd python && DATABASE_URL=$(DATABASE_URL) \
		SUPABASE_URL=$(SUPABASE_URL) \
		SUPABASE_SERVICE_KEY=$(SUPABASE_SERVICE_KEY) \
		uv run python ../scripts/seed_dev.py

seed-real-media-e2e: _ensure-e2e-deps
	./scripts/with_supabase_services.sh make _seed-real-media-e2e-raw

_seed-real-media-e2e-raw:
	cd e2e && bunx tsx seed-e2e-user.ts
	cd migrations && DATABASE_URL=$(DATABASE_URL) NEXUS_ENV=local \
		uv run --project ../python alembic upgrade head
	cd python && DATABASE_URL=$(DATABASE_URL) NEXUS_ENV=local \
		REAL_MEDIA_PROVIDER_FIXTURES=1 \
		REAL_MEDIA_FIXTURE_DIR=$$PWD/tests/fixtures/real_media \
		uv run python scripts/seed_real_media_e2e.py

check:
	make check-back
	make type-back
	make check-front
	make check-workflows

check-back:
	cd python && uv run ruff check .
	cd python && uv run ruff format --check .

type-back:
	cd python && uv run pyright

check-front:
	cd apps/web && bun run lint
	cd apps/web && bun run typecheck

check-workflows:
	actionlint .github/workflows/*.yml
	cd python && uv run zizmor ../.github/workflows

format:
	make format-back
	make fix-front

format-back:
	cd python && uv run ruff format .

fix-front:
	cd apps/web && bun run lint -- --fix

build:
	cd apps/web && bun run build

audit:
	cd python && uv sync --all-extras --locked
	cd python && uv export --locked --all-extras --no-emit-project \
		--no-emit-package llm-calling --no-emit-package web-search-tool \
		--format requirements.txt > /tmp/nexus-python-audit-requirements.txt
	cd python && uv run pip-audit --strict --no-deps --disable-pip \
		--requirement /tmp/nexus-python-audit-requirements.txt
	cd apps/web && bun audit --audit-level=high
	cd e2e && bun audit --audit-level=high
	cd node/ingest && bun audit --audit-level=high

test-unit:
	make test-back-unit
	make test-front-unit

test:
	make test-unit
	./scripts/with_test_services.sh make _test-back-db-ready _test-back-integration-raw _test-migrations-raw
	make test-front-browser

test-back-unit:
	cd python && NEXUS_ENV=test uv run pytest -v -n auto -m "unit and not integration"

test-back-integration:
	./scripts/with_test_services.sh make _test-back-db-ready _test-back-integration-raw

_test-back-db-ready:
	make migrate-test

_test-back-integration-raw:
	make _ensure-node-ingest
	cd python && NEXUS_ENV=test uv run pytest -v --tb=short \
		-m "integration and not unit and not supabase and not network and not slow" \
		--ignore=tests/test_migrations.py

test-front-unit:
	cd apps/web && bun run test:unit

test-front-browser:
	@if [ "$${CI:-}" = "true" ]; then \
		cd apps/web && bunx playwright install --with-deps chromium; \
	else \
		cd apps/web && bunx playwright install chromium; \
	fi
	cd apps/web && bun run test:browser

test-migrations:
	./scripts/with_test_services.sh make _test-migrations-raw

_test-migrations-raw:
	cd python && DATABASE_URL=$(DATABASE_URL_TEST_MIGRATIONS) NEXUS_ENV=test \
		uv run pytest -v --tb=short tests/test_migrations.py

test-supabase:
	./scripts/with_supabase_services.sh ./scripts/with_test_services.sh make _test-back-db-ready _test-supabase-raw

_test-supabase-raw:
	cd python && NEXUS_ENV=test uv run pytest -v --tb=short -m supabase

test-real-media: _ensure-e2e-deps
	./scripts/with_supabase_services.sh ./scripts/with_test_services.sh make _test-back-db-ready _test-real-media-backend-raw
	./scripts/with_supabase_services.sh make _test-real-media-e2e-raw

_test-real-media-backend-raw:
	make _ensure-node-ingest
	mkdir -p test-results
	cd python && NEXUS_ENV=local \
		REAL_MEDIA_PROVIDER_FIXTURES=1 \
		REAL_MEDIA_FIXTURE_DIR=$$PWD/tests/fixtures/real_media \
		uv run pytest -v --tb=short \
		--basetemp=../test-results/real-media-backend \
		-m real_media

test-live-providers:
	./scripts/with_supabase_services.sh ./scripts/with_test_services.sh make _test-back-db-ready _test-live-providers-raw

_test-live-providers-raw:
	make _ensure-node-ingest
	mkdir -p test-results
	cd python && NEXUS_ENV=local PODCAST_INITIAL_EPISODE_WINDOW=1 uv run pytest -v --tb=short \
		--basetemp=../test-results/live-providers \
		-m live_provider

test-e2e: _ensure-e2e-deps
	./scripts/with_supabase_services.sh make _test-e2e-raw

_test-e2e-raw:
	@API_PORT=$$(./scripts/find_port.sh $(API_PORT) api) && \
	WEB_PORT=$$(./scripts/find_port.sh $(WEB_PORT) web) && \
	echo "Running e2e with API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT" && \
	cd e2e && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT bunx playwright install --with-deps chromium && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT bun run test:e2e -- $(PLAYWRIGHT_ARGS)

_test-real-media-e2e-raw:
	@API_PORT=$$(./scripts/find_port.sh $(API_PORT) api) && \
	WEB_PORT=$$(./scripts/find_port.sh $(WEB_PORT) web) && \
	echo "Running real-media e2e with API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT" && \
	cd e2e && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT NEXUS_ENV=local E2E_REAL_MEDIA=1 bunx playwright install --with-deps chromium && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT NEXUS_ENV=local E2E_REAL_MEDIA=1 \
	REAL_MEDIA_PROVIDER_FIXTURES=1 \
	REAL_MEDIA_FIXTURE_DIR=$$PWD/../python/tests/fixtures/real_media \
	bun run test:e2e -- --project=real-media $(PLAYWRIGHT_ARGS)

test-e2e-ui: _ensure-e2e-deps
	./scripts/with_supabase_services.sh make _test-e2e-ui-raw

_test-e2e-ui-raw:
	@API_PORT=$$(./scripts/find_port.sh $(API_PORT) api) && \
	WEB_PORT=$$(./scripts/find_port.sh $(WEB_PORT) web) && \
	echo "Running e2e ui with API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT" && \
	cd e2e && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT bunx playwright install chromium && \
	API_PORT=$$API_PORT WEB_PORT=$$WEB_PORT bunx playwright test --ui

verify:
	make check
	make build
	make test
	@echo "=== verification passed ==="

verify-full:
	make verify
	make test-real-media
	make test-live-providers
	make test-e2e
	@echo "=== full verification passed ==="

_ensure-node-ingest:
	@if [ ! -d "node/ingest/node_modules" ]; then \
		echo "Installing Node.js ingest worker dependencies..."; \
		cd node/ingest && bun install --frozen-lockfile; \
	fi

_ensure-e2e-deps:
	@if [ ! -d "e2e/node_modules" ]; then \
		echo "Installing E2E dependencies..."; \
		cd e2e && bun install --frozen-lockfile; \
	fi
