/**
 * Static palette command catalog.
 *
 * Owns the global navigation/create commands and the query<->command match
 * predicate consumed by the CommandPalette component.
 */

import {
  FileText,
  FolderPlus,
  Link,
  MessageSquarePlus,
  Plus,
  Sparkles,
  Upload,
} from "lucide-react";
import type { PaletteCommand } from "@/components/palette/types";
import { getPaneRouteIcon } from "@/lib/panes/paneRouteRegistry";

export const STATIC_COMMANDS: PaletteCommand[] = [
  {
    id: "nav-oracle",
    title: "Oracle",
    keywords: ["oracle", "divination", "reading", "folio", "fortune", "sortes", "motto"],
    sectionId: "navigate",
    icon: Sparkles,
    target: { kind: "href", href: "/oracle", externalShell: true },
    source: "static",
    rank: {},
  },
  {
    id: "nav-libraries",
    title: "Libraries",
    keywords: ["collections", "sources"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/libraries"),
    target: { kind: "href", href: "/libraries", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-browse",
    title: "Browse",
    keywords: ["discover", "podcasts", "videos", "documents"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/browse"),
    target: { kind: "href", href: "/browse", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-podcasts",
    title: "Podcasts",
    keywords: ["audio", "feeds", "episodes"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/podcasts"),
    target: { kind: "href", href: "/podcasts", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-chats",
    title: "Chats",
    keywords: ["conversations", "messages"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/conversations"),
    target: { kind: "href", href: "/conversations", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-today",
    title: "Today's note",
    keywords: ["daily", "journal", "notes"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/daily"),
    target: { kind: "href", href: "/daily", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-notes",
    title: "Notes",
    keywords: ["pages", "outline", "knowledge"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/notes"),
    target: { kind: "href", href: "/notes", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-search",
    title: "Search",
    keywords: ["find", "query"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/search"),
    target: { kind: "href", href: "/search", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-settings",
    title: "Settings",
    keywords: ["preferences", "account"],
    sectionId: "navigate",
    icon: getPaneRouteIcon("/settings"),
    target: { kind: "href", href: "/settings", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-appearance",
    title: "Appearance",
    keywords: ["theme", "light", "dark"],
    sectionId: "settings",
    icon: getPaneRouteIcon("/settings/appearance"),
    target: { kind: "href", href: "/settings/appearance", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-reader-settings",
    title: "Reader Settings",
    keywords: ["typography", "font", "theme"],
    sectionId: "settings",
    icon: getPaneRouteIcon("/settings/reader"),
    target: { kind: "href", href: "/settings/reader", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-api-keys",
    title: "API Keys",
    keywords: ["credentials", "providers"],
    sectionId: "settings",
    icon: getPaneRouteIcon("/settings/keys"),
    target: { kind: "href", href: "/settings/keys", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-identities",
    title: "Linked Identities",
    keywords: ["google", "github", "oauth"],
    sectionId: "settings",
    icon: getPaneRouteIcon("/settings/identities"),
    target: { kind: "href", href: "/settings/identities", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "nav-keybindings",
    title: "Keyboard Shortcuts",
    keywords: ["keybindings", "hotkeys", "shortcuts"],
    sectionId: "settings",
    icon: getPaneRouteIcon("/settings/keybindings"),
    target: { kind: "href", href: "/settings/keybindings", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "create-conversation",
    title: "New conversation",
    keywords: ["chat", "message"],
    sectionId: "create",
    icon: MessageSquarePlus,
    target: { kind: "action", actionId: "new-conversation" },
    source: "static",
    rank: {},
  },
  {
    id: "create-page",
    title: "New page",
    keywords: ["note", "notes", "outline"],
    sectionId: "create",
    icon: Plus,
    target: { kind: "action", actionId: "create-page" },
    source: "static",
    rank: {},
  },
  {
    id: "quick-note-today",
    title: "Quick note to today",
    keywords: ["daily", "capture", "journal"],
    sectionId: "create",
    icon: FileText,
    target: { kind: "action", actionId: "quick-note" },
    source: "static",
    rank: {},
  },
  {
    id: "create-library",
    title: "New library",
    keywords: ["collection", "create"],
    sectionId: "create",
    icon: FolderPlus,
    target: { kind: "href", href: "/libraries", externalShell: false },
    source: "static",
    rank: {},
  },
  {
    id: "create-upload",
    title: "Upload file",
    keywords: ["pdf", "epub", "import", "add"],
    sectionId: "create",
    icon: Upload,
    target: { kind: "action", actionId: "add-content" },
    source: "static",
    rank: {},
  },
  {
    id: "create-url",
    title: "Add from URL",
    keywords: ["link", "paste", "import"],
    sectionId: "create",
    icon: Link,
    target: { kind: "action", actionId: "add-content" },
    source: "static",
    rank: {},
  },
  {
    id: "create-opml",
    title: "Import OPML",
    keywords: ["podcast", "opml", "import"],
    sectionId: "create",
    icon: Upload,
    target: { kind: "action", actionId: "add-opml" },
    source: "static",
    rank: {},
  },
];

export function matchesCommand(command: PaletteCommand, query: string): boolean {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return true;
  if (command.source === "search" || command.source === "ai") return true;
  if (command.title.toLowerCase().includes(normalized)) return true;
  return command.keywords.some((keyword) => keyword.toLowerCase().includes(normalized));
}
