"""Generate the browser's closed tool-projection contract.

Single source of truth: ``BROWSER_TOOL_PROJECTION_CONTRACT`` and its revision
in ``nexus.services.tool_runtime.declarations``. Run from ``python/`` with:

    uv run python scripts/generate_tool_contract_projection.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

from llm_tools import canonical_json_bytes

from nexus.services.tool_runtime.declarations import (
    BROWSER_TOOL_PROJECTION_CONTRACT,
    BROWSER_TOOL_PROJECTION_REVISION,
)

PROJECTION_RELATIVE_PATH = "apps/web/src/lib/conversations/toolContractProjection.ts"


def render_projection() -> str:
    """Return the byte-exact committed browser projection."""

    contract = canonical_json_bytes(BROWSER_TOOL_PROJECTION_CONTRACT).decode("utf-8")
    return f'''// @generated by python/scripts/generate_tool_contract_projection.py from
// BROWSER_TOOL_PROJECTION_CONTRACT in
// python/nexus/services/tool_runtime/declarations.py. Run the owning generator;
// do not edit this file by hand.

export const TOOL_CONTRACT_PROJECTION = {contract} as const;

export const TOOL_PROJECTION_REVISION = "{BROWSER_TOOL_PROJECTION_REVISION}" as const;

export type ToolProjectionField =
  (typeof TOOL_CONTRACT_PROJECTION.fields)[number];
export type ToolEffect = (typeof TOOL_CONTRACT_PROJECTION.effects)[number];
export type ToolResultKind =
  (typeof TOOL_CONTRACT_PROJECTION.result_kinds)[number];
export type ToolErrorType =
  (typeof TOOL_CONTRACT_PROJECTION.error_types)[number];
export type ToolRecordKind =
  (typeof TOOL_CONTRACT_PROJECTION.record_kinds)[number];
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="check committed bytes without writing"
    )
    args = parser.parse_args()
    content = render_projection()
    path = Path(__file__).resolve().parents[2] / PROJECTION_RELATIVE_PATH
    if args.check:
        if path.read_bytes() != content.encode("utf-8"):
            raise SystemExit(
                f"error: {PROJECTION_RELATIVE_PATH} is stale; run: "
                "cd python && uv run python scripts/generate_tool_contract_projection.py"
            )
        print(f"{PROJECTION_RELATIVE_PATH} is current")
        return
    path.write_text(content, encoding="utf-8")
    print(f"wrote {PROJECTION_RELATIVE_PATH} ({len(content)} chars)")


if __name__ == "__main__":
    main()
