"""Export the backend-owned chat revision to the browser."""

from pathlib import Path

from nexus.schemas.chat_contract import CHAT_CONTRACT_REVISION


def main() -> None:
    output = (
        Path(__file__).resolve().parents[2]
        / "apps/web/src/lib/conversations/chatContractRevision.ts"
    )
    output.write_text(
        "// @generated by python/scripts/generate_chat_contract_revision.py\n"
        f'export const CHAT_CONTRACT_REVISION = "{CHAT_CONTRACT_REVISION}" as const;\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
