"""Generate the browser static resource-capability projection.

Single source of truth: ``RESOURCE_ITEM_CAPABILITIES`` in
``python/nexus/services/resource_items/capabilities.py``. This script emits the
committed browser projection ``apps/web/src/lib/resources/resourceCapabilities.ts``
byte-for-byte, so the backend static capabilities and the frontend projection
cannot drift. The ``resource-capability-drift`` policy check
(``python/nexus_test_control/policy.py``) re-runs :func:`render_projection` and
byte-compares it to the committed file, failing ``./scripts/test`` on drift.

    cd python && uv run python scripts/generate_resource_capabilities.py
    make generate-resource-capabilities
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

from nexus.services.resource_items.capabilities import (
    RESOURCE_ITEM_CAPABILITIES,
    ResourceInspectorResourcePolicy,
    ResourceItemCapability,
    ResourceUserRelationPolicy,
)

PROJECTION_RELATIVE_PATH = "apps/web/src/lib/resources/resourceCapabilities.ts"

# The exact set of `ResourceItemCapability` fields `_render_capability` emits.
# Asserting this equals the backend dataclass fields turns a NEW backend field
# into a hard generator failure — otherwise a field added to the dataclass would
# be silently dropped from the projection with generator-output still equal to
# the committed file, and no `resource-capability-drift` would fire.
_EMITTED_CAPABILITY_FIELDS = frozenset(
    {
        "user_relation",
        "sharing",
        "library_placement",
        "attachable",
        "chat_subject",
        "readable",
        "inspectable",
        "inspector_policy",
        "citable_result_type",
        "app_search_scope",
        "conversation_search_scope",
        "citation_output_source",
        "prompt_render",
        "expansion_policy",
        "adjacency_source",
        "adjacency_target",
    }
)

# The frontend projection whose prose (imports, types, interfaces, helpers) is
# hand-authored and whose ``RESOURCE_CAPABILITIES`` table is generated from the
# backend dataclass table below. Line-length matches the frontend eslint
# convention (`make fix-front`), so the emitted table is formatter-stable.
_PRINT_WIDTH = 80

_HEADER = (
    "// @generated by python/scripts/generate_resource_capabilities.py from\n"
    "// RESOURCE_ITEM_CAPABILITIES in\n"
    "// python/nexus/services/resource_items/capabilities.py. Run\n"
    "// `make generate-resource-capabilities` to regenerate. Do not edit by hand.\n"
)

_PREFIX = """import type { ResourceScheme } from "@/lib/resourceGraph/resourceRef";
import type { ShareMode } from "@/lib/sharing/types";

export type ResourceChatSubjectMode =
  "none" | "label" | "scope" | "readable" | "quote" | "generated_output";
export type ResourceReadMode = "none" | "scope" | "body" | "media";
export type ResourceInspectMode = "none" | "media_document_map";
export type ResourcePromptRenderMode =
  "none" | "label" | "inline_body" | "quote";
export type ResourceExpansionPolicy =
  | "none"
  | "media_owned_reader_children"
  | "page_note_blocks"
  | "note_block_owned_evidence"
  | "artifact_revisions";
export type LibraryPlacementMode = "None" | "ManageEntries";

export function isLibraryPlacementMode(
  value: unknown,
): value is LibraryPlacementMode {
  return value === "None" || value === "ManageEntries";
}

// Mirrors backend `ResourceUserRelationPolicy`
// (python/nexus/services/resource_items/capabilities.py). Replaces the scalar
// `linkable` boolean, which could not distinguish a direct durable endpoint
// from raw material a search hit must materialize into a `passage_anchor`
// before it can be linked (universal-link-authoring-hard-cutover.md,
// Invariant 4).
export type UserLinkTargetMode = "none" | "direct" | "materialize_passage";

export interface ResourceUserRelationPolicy {
  userLinkSource: boolean;
  userLinkTarget: UserLinkTargetMode;
}

// Mirrors backend `ResourceInspectorSurfaceRole`/`ResourceInspectorPolicy`
// (python/nexus/services/resource_items/capabilities.py). Closed-code union
// values are PascalCase per docs/rules/naming.md ("Enums are PascalCase
// strings"), matching every other new vocabulary item in
// docs/cutovers/resource-inspector-and-universal-dossiers-hard-cutover.md
// (Capability Contract).
export type ResourceInspectorSurfaceRole =
  "Contents" | "LinkedItems" | "Forks" | "Dossier";

// Which concrete LinkedItems surface a subject's Inspector resolves to:
// Media -> Evidence, Conversation -> Context, everything else -> Connections.
export type ResourceInspectorLinkedItemsSurface =
  "MediaEvidence" | "ConversationContext" | "ResourceConnections";

// Only Conversation ever carries a Forks surface.
export type ResourceInspectorForksSurface = "ConversationForks";

export interface ResourceInspectorResourcePolicy {
  linkedItems: ResourceInspectorLinkedItemsSurface;
  forks: ResourceInspectorForksSurface | null;
  /** Fallback preference order, NOT tab display order. Always ends in the
   * always-published Dossier role. `useResourceInspector` selects the first
   * concrete surface currently published. */
  defaultSurfaceOrder: readonly ResourceInspectorSurfaceRole[];
}

// `None | Resource{...}`: only the 7 Dossier-eligible subjects (media,
// conversation, library, podcast, contributor, page, note_block) carry a
// non-null policy. `Resource` implies Dossier eligibility. Contents
// eligibility is NOT re-modeled here — it derives from the already-owned
// `inspectable` capability below (no `contents_provider` field).
export type ResourceInspectorPolicy = ResourceInspectorResourcePolicy | null;

export interface ResourceCapabilityProjection {
  userRelation: ResourceUserRelationPolicy;
  sharing: ShareMode;
  libraryPlacement: LibraryPlacementMode;
  attachable: boolean;
  chatSubject: ResourceChatSubjectMode;
  readable: ResourceReadMode;
  inspectable: ResourceInspectMode;
  inspectorPolicy: ResourceInspectorPolicy;
  citableResultType: string | null;
  appSearchScope: boolean;
  conversationSearchScope: boolean;
  citationOutputSource: boolean;
  promptRender: ResourcePromptRenderMode;
  expansionPolicy: ResourceExpansionPolicy;
  adjacencySource: boolean;
  adjacencyTarget: boolean;
}

export const SYNAPSE_SOURCE_SCHEMES = [
  "media",
  "page",
  "note_block",
  "highlight",
] as const satisfies readonly ResourceScheme[];
"""

_SUFFIX = """export function resourceCapabilityForScheme(
  scheme: ResourceScheme,
): ResourceCapabilityProjection {
  return RESOURCE_CAPABILITIES[scheme];
}

/** Whether `scheme` can be the target of a durable, direct-endpoint Link or
 * note reference. `materialize_passage` targets are raw material a search hit
 * must convert into a `passage_anchor` first (Invariant 4); they are never
 * themselves a direct edge/reference endpoint. Mirrors backend
 * `resource_can_be_note_reference_target` / the `note_reference_target`
 * property on `ResourceUserRelationPolicy`. */
export function resourceCanBeNoteReferenceTarget(
  scheme: ResourceScheme,
): boolean {
  return RESOURCE_CAPABILITIES[scheme].userRelation.userLinkTarget === "direct";
}

export function resourceSchemeIsAppSearchScope(
  scheme: ResourceScheme,
): boolean {
  return RESOURCE_CAPABILITIES[scheme].appSearchScope;
}
"""


def _bool(value: bool) -> str:
    return "true" if value else "false"


def _optional_string(value: str | None) -> str:
    return "null" if value is None else f'"{value}"'


def _render_user_relation(relation: ResourceUserRelationPolicy) -> list[str]:
    source = _bool(relation.user_link_source)
    target = relation.user_link_target
    inline = f'{{ userLinkSource: {source}, userLinkTarget: "{target}" }}'
    candidate = f"    userRelation: {inline},"
    if len(candidate) <= _PRINT_WIDTH:
        return [candidate]
    return [
        "    userRelation: {",
        f"      userLinkSource: {source},",
        f'      userLinkTarget: "{target}",',
        "    },",
    ]


def _render_inspector_policy(policy: ResourceInspectorResourcePolicy | None) -> list[str]:
    if policy is None:
        return ["    inspectorPolicy: null,"]
    surfaces = ", ".join(f'"{role.value}"' for role in policy.default_surface_order)
    forks = _optional_string(policy.forks)
    return [
        "    inspectorPolicy: {",
        f'      linkedItems: "{policy.linked_items}",',
        f"      forks: {forks},",
        f"      defaultSurfaceOrder: [{surfaces}],",
        "    },",
    ]


def _render_capability(scheme: str, capability: ResourceItemCapability) -> list[str]:
    lines = [f"  {scheme}: {{"]
    lines.extend(_render_user_relation(capability.user_relation))
    lines.append(f'    sharing: "{capability.sharing}",')
    lines.append(f'    libraryPlacement: "{capability.library_placement}",')
    lines.append(f"    attachable: {_bool(capability.attachable)},")
    lines.append(f'    chatSubject: "{capability.chat_subject}",')
    lines.append(f'    readable: "{capability.readable}",')
    lines.append(f'    inspectable: "{capability.inspectable}",')
    lines.extend(_render_inspector_policy(capability.inspector_policy))
    lines.append(f"    citableResultType: {_optional_string(capability.citable_result_type)},")
    lines.append(f"    appSearchScope: {_bool(capability.app_search_scope)},")
    lines.append(f"    conversationSearchScope: {_bool(capability.conversation_search_scope)},")
    lines.append(f"    citationOutputSource: {_bool(capability.citation_output_source)},")
    lines.append(f'    promptRender: "{capability.prompt_render}",')
    lines.append(f'    expansionPolicy: "{capability.expansion_policy}",')
    lines.append(f"    adjacencySource: {_bool(capability.adjacency_source)},")
    lines.append(f"    adjacencyTarget: {_bool(capability.adjacency_target)},")
    lines.append("  },")
    return lines


def render_projection() -> str:
    """Return the byte-exact content of the committed browser projection."""
    backend_fields = {field.name for field in dataclasses.fields(ResourceItemCapability)}
    if backend_fields != _EMITTED_CAPABILITY_FIELDS:
        raise AssertionError(
            "ResourceItemCapability fields changed; update _render_capability and "
            "_EMITTED_CAPABILITY_FIELDS to project them. "
            f"backend-only={backend_fields - _EMITTED_CAPABILITY_FIELDS}; "
            f"emitter-only={_EMITTED_CAPABILITY_FIELDS - backend_fields}"
        )
    body: list[str] = ["export const RESOURCE_CAPABILITIES = {"]
    for scheme, capability in RESOURCE_ITEM_CAPABILITIES.items():
        body.extend(_render_capability(scheme, capability))
    body.append("} as const satisfies Record<ResourceScheme, ResourceCapabilityProjection>;")
    table = "\n".join(body) + "\n"
    return f"{_HEADER}\n{_PREFIX}\n{table}\n{_SUFFIX}"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def main() -> None:
    content = render_projection()
    path = _repo_root() / PROJECTION_RELATIVE_PATH
    path.write_text(content, encoding="utf-8")
    print(f"wrote {PROJECTION_RELATIVE_PATH} ({len(content)} chars)")


if __name__ == "__main__":
    main()
