#!/usr/bin/env python
"""Seed E2E test data for zero-mock Playwright tests.

This script:
1) Ensures the E2E user exists (created by e2e/seed-e2e-user.ts).
2) Bootstraps the app user + default library in Nexus DB.
3) Creates a PDF upload stub through the real upload service.
4) Uploads a generated multi-page PDF bytes payload to Supabase Storage.
5) Confirms ingest and runs synchronous PDF extraction for quote-ready artifacts.
6) Seeds one deterministic password-protected failure media row for degrade-path UI tests.
7) Seeds a non-PDF web article with highlights for linked-items tests.
8) Seeds a test API key so the models endpoint returns data and the Send button works.
9) Seeds an EPUB with 3 chapters for EPUB reader tests.
10) Seeds transcript-ready + transcript-unavailable YouTube video rows for media-pane E2E.
11) Writes upload fixture bytes + seeded metadata to e2e/.seed/.
"""

from __future__ import annotations

import json
import os
import sys
import zipfile
from datetime import UTC, datetime
from html import escape
from io import BytesIO
from pathlib import Path
from uuid import UUID

import fitz
import httpx
from sqlalchemy import select, text

from nexus.config import get_settings
from nexus.db.models import Annotation, FailureStage, Fragment, Media, ProcessingStatus
from nexus.db.session import create_session_factory
from nexus.schemas.highlights import CreateHighlightRequest
from nexus.services.bootstrap import ensure_user_and_default_library
from nexus.services.epub_ingest import EpubExtractionError
from nexus.services.highlights import create_highlight_for_fragment
from nexus.services.media import create_or_reuse_youtube_video, create_provisional_web_article
from nexus.services.pdf_ingest import PdfExtractionError
from nexus.services.upload import confirm_ingest, init_upload
from nexus.tasks.ingest_epub import run_epub_ingest_sync
from nexus.tasks.ingest_pdf import run_pdf_ingest_sync

E2E_USER_EMAIL = os.getenv("E2E_USER_EMAIL", "e2e-test@nexus.local")
PDF_PAGE_COUNT = 80
SEED_FILE_RELATIVE = Path("e2e/.seed/pdf-media.json")
NON_PDF_SEED_FILE_RELATIVE = Path("e2e/.seed/non-pdf-media.json")
EPUB_SEED_FILE_RELATIVE = Path("e2e/.seed/epub-media.json")
YOUTUBE_SEED_FILE_RELATIVE = Path("e2e/.seed/youtube-media.json")
READER_RESUME_SEED_FILE_RELATIVE = Path("e2e/.seed/reader-resume-media.json")
UPLOAD_FIXTURE_RELATIVE = Path("e2e/.seed/upload-source.pdf")
NON_PDF_SOURCE_URL = "https://example.com/e2e-linked-items-seed"
READER_RESUME_WEB_SOURCE_URL = "https://example.com/e2e-reader-resume-web-seed"
YOUTUBE_VIDEO_ID = "s8E2Evid001"
YOUTUBE_PLAYBACK_ONLY_VIDEO_ID = "s8E2Evid002"
YOUTUBE_WATCH_URL = f"https://www.youtube.com/watch?v={YOUTUBE_VIDEO_ID}"
YOUTUBE_PLAYBACK_ONLY_WATCH_URL = (
    f"https://www.youtube.com/watch?v={YOUTUBE_PLAYBACK_ONLY_VIDEO_ID}"
)
YOUTUBE_EMBED_URL = f"https://www.youtube.com/embed/{YOUTUBE_VIDEO_ID}"
YOUTUBE_TRANSCRIPT_SEGMENTS = [
    {
        "canonical_text": "S8 E2E segment alpha intro line.",
        "speaker_label": "Host",
        "t_start_ms": 4_000,
        "t_end_ms": 8_000,
    },
    {
        "canonical_text": "S8 E2E segment beta seek target.",
        "speaker_label": "Guest",
        "t_start_ms": 12_000,
        "t_end_ms": 17_000,
    },
]

# EPUB chapter content for deterministic tests
EPUB_CHAPTERS = [
    {
        "title": "Chapter 1: Introduction",
        "body": "This is the introduction chapter of the E2E test EPUB. "
        "It contains deterministic content for automated testing. "
        "The EPUB reader should display this text correctly.",
    },
    {
        "title": "Chapter 2: Core Concepts",
        "body": "This chapter covers core concepts for E2E testing. "
        "Highlights and annotations should work across chapter boundaries. "
        "Navigation between chapters is a key feature to verify.",
    },
    {
        "title": "Chapter 3: Conclusion",
        "body": "This is the final chapter of the E2E test EPUB. "
        "All three chapters should appear in the table of contents. "
        "Chapter navigation should allow moving between all chapters.",
    },
]

EPUB_TOC_ANCHOR_CHAPTER_INDEX = 0
EPUB_TOC_ANCHOR_ID = "e2e-deep-anchor-target"
EPUB_TOC_ANCHOR_NAME = "e2e-deep-anchor-legacy-name"
EPUB_TOC_ANCHOR_LABEL = "Chapter 1: Deep Anchor Target"
EPUB_TOC_ANCHOR_HEADING = "Deep Anchor Target"
READER_RESUME_WEB_ANCHOR_TEXT = "reader resume anchor target omega"
READER_RESUME_PDF_PAGE_COUNT = 8


def _build_pdf_bytes(page_count: int) -> bytes:
    """Generate a simple multi-page PDF suitable for PDF.js rendering."""
    doc = fitz.open()
    for page_idx in range(page_count):
        page = doc.new_page()
        page.insert_text(
            (72, 72),
            f"E2E PDF signed-url expiry seed\nPage {page_idx + 1} of {page_count}",
            fontsize=14,
        )
        page.insert_text(
            (72, 120),
            "This file is generated by python/scripts/seed_e2e_data.py",
            fontsize=11,
        )
    try:
        return doc.tobytes()
    finally:
        doc.close()


def _build_epub_bytes(variant_id: str = "base") -> bytes:
    """Generate a minimal valid EPUB with 3 chapters."""
    safe_variant = "".join(ch for ch in variant_id if ch.isalnum() or ch in ("-", "_")) or "base"
    epub_uid = f"e2e-test-epub-{safe_variant}"
    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # mimetype must be first and uncompressed
        zf.writestr("mimetype", "application/epub+zip", compress_type=zipfile.ZIP_STORED)

        # META-INF/container.xml
        zf.writestr(
            "META-INF/container.xml",
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">\n'
            "  <rootfiles>\n"
            '    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>\n'
            "  </rootfiles>\n"
            "</container>",
        )

        # Build spine items and manifest items
        manifest_items = []
        spine_items = []
        nav_points = []
        nav_play_order = 1
        for idx, ch in enumerate(EPUB_CHAPTERS):
            fname = f"chapter{idx + 1}.xhtml"
            manifest_items.append(
                f'    <item id="ch{idx + 1}" href="{fname}" media-type="application/xhtml+xml"/>'
            )
            spine_items.append(f'    <itemref idref="ch{idx + 1}"/>')
            nav_points.append(
                f'    <navPoint id="nav{idx + 1}" playOrder="{nav_play_order}">\n'
                f"      <navLabel><text>{ch['title']}</text></navLabel>\n"
                f'      <content src="{fname}"/>\n'
                f"    </navPoint>"
            )
            nav_play_order += 1

            chapter_body_html = f"<h1>{ch['title']}</h1>\n<p>{ch['body']}</p>\n"

            if idx == EPUB_TOC_ANCHOR_CHAPTER_INDEX:
                pre_anchor = "".join(
                    f"<p>Deterministic pre-anchor filler paragraph {n} for E2E.</p>\n"
                    for n in range(1, 17)
                )
                post_anchor = "".join(
                    f"<p>Deterministic post-anchor filler paragraph {n} for E2E.</p>\n"
                    for n in range(1, 9)
                )
                chapter_body_html = (
                    f"<h1>{ch['title']}</h1>\n"
                    f"<p>{ch['body']}</p>\n"
                    f"{pre_anchor}"
                    f'<h2 id="{EPUB_TOC_ANCHOR_ID}">{EPUB_TOC_ANCHOR_HEADING}</h2>\n'
                    f'<a name="{EPUB_TOC_ANCHOR_NAME}"></a>\n'
                    "<p>Anchor target landing paragraph for deterministic E2E checks.</p>\n"
                    f"{post_anchor}"
                )
                nav_points.append(
                    f'    <navPoint id="nav{idx + 1}-anchor" playOrder="{nav_play_order}">\n'
                    f"      <navLabel><text>{EPUB_TOC_ANCHOR_LABEL}</text></navLabel>\n"
                    f'      <content src="{fname}#{EPUB_TOC_ANCHOR_ID}"/>\n'
                    f"    </navPoint>"
                )
                nav_play_order += 1

            # Chapter XHTML
            zf.writestr(
                f"OEBPS/{fname}",
                '<?xml version="1.0" encoding="UTF-8"?>\n'
                "<!DOCTYPE html>\n"
                '<html xmlns="http://www.w3.org/1999/xhtml">\n'
                f"<head><title>{ch['title']}</title></head>\n"
                f"<body>\n{chapter_body_html}</body>\n"
                "</html>",
            )

        # Navigation document (toc.ncx)
        zf.writestr(
            "OEBPS/toc.ncx",
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">\n'
            "  <head>\n"
            f'    <meta name="dtb:uid" content="{epub_uid}"/>\n'
            "  </head>\n"
            "  <docTitle><text>E2E Test EPUB</text></docTitle>\n"
            "  <navMap>\n" + "\n".join(nav_points) + "\n  </navMap>\n"
            "</ncx>",
        )

        # content.opf
        zf.writestr(
            "OEBPS/content.opf",
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="uid" version="2.0">\n'
            '  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">\n'
            f'    <dc:identifier id="uid">{epub_uid}</dc:identifier>\n'
            "    <dc:title>E2E Test EPUB</dc:title>\n"
            "    <dc:language>en</dc:language>\n"
            "  </metadata>\n"
            "  <manifest>\n" + "\n".join(manifest_items) + "\n"
            '    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>\n'
            "  </manifest>\n"
            '  <spine toc="ncx">\n' + "\n".join(spine_items) + "\n  </spine>\n"
            "</package>",
        )

    return buf.getvalue()


def _fetch_e2e_user_id(supabase_url: str, service_key: str, email: str) -> UUID:
    """Lookup E2E auth user ID via Supabase admin API."""
    url = f"{supabase_url.rstrip('/')}/auth/v1/admin/users"
    headers = {
        "Authorization": f"Bearer {service_key}",
        "apikey": service_key,
    }
    with httpx.Client() as client:
        response = client.get(url, headers=headers, timeout=30.0)
    if response.status_code != 200:
        raise RuntimeError(f"Failed to list auth users: {response.status_code} {response.text}")

    payload = response.json()
    users = payload.get("users", [])
    for user in users:
        if user.get("email") == email:
            return UUID(user["id"])

    raise RuntimeError(f"E2E auth user not found for {email}. Run e2e/seed-e2e-user.ts first.")


def _upload_to_signed_url(
    *,
    supabase_url: str,
    service_key: str,
    bucket: str,
    storage_path: str,
    token: str,
    content: bytes,
    content_type: str = "application/pdf",
) -> None:
    """Upload bytes through Supabase signed-upload endpoint."""
    url = f"{supabase_url.rstrip('/')}/storage/v1/object/upload/sign/{bucket}/{storage_path}"
    headers = {
        "Authorization": f"Bearer {service_key}",
        "apikey": service_key,
        "Content-Type": content_type,
        "x-upsert": "false",
    }
    with httpx.Client() as client:
        response = client.put(
            url,
            params={"token": token},
            headers=headers,
            content=content,
            timeout=60.0,
        )

    if response.status_code not in (200, 201):
        raise RuntimeError(
            f"Failed to upload via signed URL: {response.status_code} {response.text}"
        )


def _write_upload_fixture(content: bytes) -> str:
    """Persist a deterministic upload fixture used by Playwright."""
    repo_root = Path(__file__).resolve().parents[2]
    fixture_path = repo_root / UPLOAD_FIXTURE_RELATIVE
    fixture_path.parent.mkdir(parents=True, exist_ok=True)
    fixture_path.write_bytes(content)
    print(f"Wrote E2E upload fixture: {fixture_path}")
    # Playwright runs with CWD=e2e, so keep path relative to e2e/.
    return fixture_path.relative_to(repo_root / "e2e").as_posix()


def _write_seed_file(
    media_id: str,
    title: str,
    page_count: int,
    upload_fixture_path: str,
    password_media_id: str,
) -> None:
    """Persist seeded media metadata for Playwright tests."""
    repo_root = Path(__file__).resolve().parents[2]
    seed_path = repo_root / SEED_FILE_RELATIVE
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    seed_payload = {
        "media_id": media_id,
        "title": title,
        "page_count": page_count,
        "upload_fixture_path": upload_fixture_path,
        "password_media_id": password_media_id,
        "seeded_at": datetime.now(UTC).isoformat(),
    }
    seed_path.write_text(json.dumps(seed_payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote E2E PDF seed metadata: {seed_path}")


def _build_non_pdf_fragment_payload() -> tuple[str, str, str, str]:
    """Return deterministic non-PDF canonical/html payload + focus/quote token text."""
    quote_exact = "e2e non-pdf quote target alpha"
    focus_exact = "e2e non-pdf focus target omega"

    lines: list[str] = []
    for idx in range(1, 181):
        if idx == 8:
            lines.append(f"section {idx:03d} includes {quote_exact} for quote-to-chat.")
        elif idx == 170:
            lines.append(f"section {idx:03d} includes {focus_exact} for focus+scroll.")
        else:
            lines.append(
                f"section {idx:03d} filler content for linked-items non-pdf alignment behavior."
            )

    canonical_text = "\n".join(lines)
    html_sanitized = "".join(f"<p>{escape(line)}</p>" for line in lines)
    return canonical_text, html_sanitized, quote_exact, focus_exact


def _write_non_pdf_seed_file(
    *,
    media_id: str,
    fragment_id: str,
    quote_highlight_id: str,
    focus_highlight_id: str,
    quote_exact: str,
    focus_exact: str,
) -> None:
    """Persist seeded non-PDF media metadata for linked-items E2E tests."""
    repo_root = Path(__file__).resolve().parents[2]
    seed_path = repo_root / NON_PDF_SEED_FILE_RELATIVE
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    seed_payload = {
        "media_id": media_id,
        "fragment_id": fragment_id,
        "quote_highlight_id": quote_highlight_id,
        "focus_highlight_id": focus_highlight_id,
        "quote_exact": quote_exact,
        "focus_exact": focus_exact,
        "seeded_at": datetime.now(UTC).isoformat(),
    }
    seed_path.write_text(json.dumps(seed_payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote E2E non-PDF seed metadata: {seed_path}")


def _write_epub_seed_file(
    *,
    media_id: str,
    chapter_count: int,
    chapter_titles: list[str],
    toc_anchor_label: str,
    toc_anchor_target_id: str,
    toc_anchor_heading: str,
) -> None:
    """Persist seeded EPUB media metadata for Playwright tests."""
    repo_root = Path(__file__).resolve().parents[2]
    seed_path = repo_root / EPUB_SEED_FILE_RELATIVE
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    seed_payload = {
        "media_id": media_id,
        "chapter_count": chapter_count,
        "chapter_titles": chapter_titles,
        "toc_anchor_label": toc_anchor_label,
        "toc_anchor_target_id": toc_anchor_target_id,
        "toc_anchor_heading": toc_anchor_heading,
        "seeded_at": datetime.now(UTC).isoformat(),
    }
    seed_path.write_text(json.dumps(seed_payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote E2E EPUB seed metadata: {seed_path}")


def _write_youtube_seed_file(
    *,
    media_id: str,
    playback_only_media_id: str,
    watch_url: str,
    embed_url: str,
    seek_segment_text: str,
    seek_segment_start_ms: int,
) -> None:
    """Persist seeded YouTube media metadata for transcript media E2E tests."""
    repo_root = Path(__file__).resolve().parents[2]
    seed_path = repo_root / YOUTUBE_SEED_FILE_RELATIVE
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    seed_payload = {
        "media_id": media_id,
        "playback_only_media_id": playback_only_media_id,
        "watch_url": watch_url,
        "embed_url": embed_url,
        "seek_segment_text": seek_segment_text,
        "seek_segment_start_ms": seek_segment_start_ms,
        "seeded_at": datetime.now(UTC).isoformat(),
    }
    seed_path.write_text(json.dumps(seed_payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote E2E YouTube seed metadata: {seed_path}")


def _write_reader_resume_seed_file(
    *,
    web_media_id: str,
    web_anchor_text: str,
    epub_media_id: str,
    epub_chapter_titles: list[str],
    pdf_media_id: str,
    pdf_page_count: int,
) -> None:
    """Persist dedicated media IDs for reader resume E2E coverage."""
    repo_root = Path(__file__).resolve().parents[2]
    seed_path = repo_root / READER_RESUME_SEED_FILE_RELATIVE
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "web_media_id": web_media_id,
        "web_anchor_text": web_anchor_text,
        "epub_media_id": epub_media_id,
        "epub_chapter_titles": epub_chapter_titles,
        "pdf_media_id": pdf_media_id,
        "pdf_page_count": pdf_page_count,
        "seeded_at": datetime.now(UTC).isoformat(),
    }
    seed_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote E2E reader-resume seed metadata: {seed_path}")


def _clear_fragment_artifacts(db, media_id: UUID) -> None:
    """Clear fragments/highlights/annotations attached to media transcript content."""
    db.execute(
        text(
            """
            DELETE FROM annotations
            WHERE highlight_id IN (
                SELECT h.id
                FROM highlights h
                JOIN fragments f ON f.id = h.fragment_id
                WHERE f.media_id = :media_id
            )
            """
        ),
        {"media_id": media_id},
    )
    db.execute(
        text(
            """
            DELETE FROM highlights
            WHERE fragment_id IN (
                SELECT id
                FROM fragments
                WHERE media_id = :media_id
            )
            """
        ),
        {"media_id": media_id},
    )
    db.execute(
        text("DELETE FROM fragments WHERE media_id = :media_id"),
        {"media_id": media_id},
    )


def _seed_non_pdf_linked_items_media(session_factory, user_id: UUID) -> None:
    """Seed deterministic web-article media with highlights for linked-items E2E."""
    canonical_text, html_sanitized, quote_exact, focus_exact = _build_non_pdf_fragment_payload()

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        provisional = create_provisional_web_article(
            db=db,
            viewer_id=user_id,
            url=NON_PDF_SOURCE_URL,
            enqueue_task=False,
        )
        media_id = provisional.media_id

    with session_factory() as db:
        media = db.execute(select(Media).where(Media.id == media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Non-PDF seed media missing: {media_id}")

        now = datetime.now(UTC)
        media.title = "E2E linked-items web article seed"
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_started_at = now
        media.processing_completed_at = now
        media.updated_at = now

        fragment = Fragment(
            media_id=media_id,
            idx=0,
            canonical_text=canonical_text,
            html_sanitized=html_sanitized,
        )
        db.add(fragment)
        db.flush()

        quote_start = canonical_text.index(quote_exact)
        quote_end = quote_start + len(quote_exact)
        focus_start = canonical_text.index(focus_exact)
        focus_end = focus_start + len(focus_exact)

        quote_highlight = create_highlight_for_fragment(
            db=db,
            viewer_id=user_id,
            fragment_id=fragment.id,
            req=CreateHighlightRequest(
                start_offset=quote_start,
                end_offset=quote_end,
                color="yellow",
            ),
        )
        focus_highlight = create_highlight_for_fragment(
            db=db,
            viewer_id=user_id,
            fragment_id=fragment.id,
            req=CreateHighlightRequest(
                start_offset=focus_start,
                end_offset=focus_end,
                color="blue",
            ),
        )

        db.add(
            Annotation(
                highlight_id=quote_highlight.id,
                body="Seeded note for non-PDF linked-items e2e.",
            )
        )
        db.add(
            Annotation(
                highlight_id=focus_highlight.id,
                body="Seeded focus note for non-PDF linked-items e2e.",
            )
        )
        db.commit()

    _write_non_pdf_seed_file(
        media_id=str(media_id),
        fragment_id=str(fragment.id),
        quote_highlight_id=str(quote_highlight.id),
        focus_highlight_id=str(focus_highlight.id),
        quote_exact=quote_exact,
        focus_exact=focus_exact,
    )
    print(f"Seeded non-PDF linked-items media for E2E: {media_id}")


def _seed_youtube_transcript_media(session_factory, user_id: UUID) -> None:
    """Seed transcript-ready + transcript-unavailable YouTube media for E2E."""
    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        transcript_resp = create_or_reuse_youtube_video(
            db=db,
            viewer_id=user_id,
            url=YOUTUBE_WATCH_URL,
            enqueue_task=False,
        )
        transcript_media_id = transcript_resp.media_id

    with session_factory() as db:
        media = db.execute(
            select(Media).where(Media.id == transcript_media_id)
        ).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"YouTube transcript-ready media missing: {transcript_media_id}")

        _clear_fragment_artifacts(db, transcript_media_id)

        now = datetime.now(UTC)
        media.title = "E2E YouTube transcript-ready seed"
        media.canonical_url = YOUTUBE_WATCH_URL
        media.canonical_source_url = YOUTUBE_WATCH_URL
        media.external_playback_url = YOUTUBE_WATCH_URL
        media.provider = "youtube"
        media.provider_id = YOUTUBE_VIDEO_ID
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_started_at = now
        media.processing_completed_at = now
        media.updated_at = now

        for idx, segment in enumerate(YOUTUBE_TRANSCRIPT_SEGMENTS):
            db.add(
                Fragment(
                    media_id=transcript_media_id,
                    idx=idx,
                    canonical_text=segment["canonical_text"],
                    html_sanitized=f"<p>{escape(segment['canonical_text'])}</p>",
                    t_start_ms=segment["t_start_ms"],
                    t_end_ms=segment["t_end_ms"],
                    speaker_label=segment["speaker_label"],
                )
            )

        db.commit()

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        playback_only_resp = create_or_reuse_youtube_video(
            db=db,
            viewer_id=user_id,
            url=YOUTUBE_PLAYBACK_ONLY_WATCH_URL,
            enqueue_task=False,
        )
        playback_only_media_id = playback_only_resp.media_id

    with session_factory() as db:
        playback_only_media = db.execute(
            select(Media).where(Media.id == playback_only_media_id)
        ).scalar_one_or_none()
        if playback_only_media is None:
            raise RuntimeError(f"YouTube playback-only media missing: {playback_only_media_id}")

        _clear_fragment_artifacts(db, playback_only_media_id)

        now = datetime.now(UTC)
        playback_only_media.title = "E2E YouTube playback-only seed"
        playback_only_media.canonical_url = YOUTUBE_PLAYBACK_ONLY_WATCH_URL
        playback_only_media.canonical_source_url = YOUTUBE_PLAYBACK_ONLY_WATCH_URL
        playback_only_media.external_playback_url = YOUTUBE_PLAYBACK_ONLY_WATCH_URL
        playback_only_media.provider = "youtube"
        playback_only_media.provider_id = YOUTUBE_PLAYBACK_ONLY_VIDEO_ID
        playback_only_media.processing_status = ProcessingStatus.failed
        playback_only_media.failure_stage = FailureStage.transcribe
        playback_only_media.last_error_code = "E_TRANSCRIPT_UNAVAILABLE"
        playback_only_media.last_error_message = "Transcript unavailable in seed fixture"
        playback_only_media.failed_at = now
        playback_only_media.processing_completed_at = now
        playback_only_media.updated_at = now
        db.commit()

    seek_segment = YOUTUBE_TRANSCRIPT_SEGMENTS[1]
    _write_youtube_seed_file(
        media_id=str(transcript_media_id),
        playback_only_media_id=str(playback_only_media_id),
        watch_url=YOUTUBE_WATCH_URL,
        embed_url=YOUTUBE_EMBED_URL,
        seek_segment_text=seek_segment["canonical_text"],
        seek_segment_start_ms=seek_segment["t_start_ms"],
    )
    print(f"Seeded YouTube transcript media for E2E: {transcript_media_id}")
    print(f"Seeded YouTube playback-only media for E2E: {playback_only_media_id}")


def _seed_api_key(session_factory, user_id: UUID) -> None:
    """Seed a test API key so the models endpoint returns data.

    Inserts directly into the DB to avoid requiring NEXUS_KEY_ENCRYPTION_KEY.
    The key is fake and never used for real API calls — we just need a row
    with status='untested' so get_usable_key_providers() returns {'openai'}
    and the models endpoint returns model data.
    """
    from nexus.db.models import UserApiKey

    with session_factory() as db:
        existing = db.scalars(
            select(UserApiKey).where(
                UserApiKey.user_id == user_id,
                UserApiKey.provider == "openai",
            )
        ).first()

        if existing:
            if existing.status == "revoked":
                existing.status = "untested"
                existing.revoked_at = None
                db.commit()
                print("Reactivated existing E2E test API key (provider=openai)")
            else:
                print("E2E test API key already exists (provider=openai)")
            return

        key = UserApiKey(
            user_id=user_id,
            provider="openai",
            encrypted_key=b"fake-e2e-ciphertext-pad!",
            key_nonce=b"fake-e2e-nonce-24bytesXX",
            master_key_version=1,
            key_fingerprint="0000",
            status="untested",
        )
        db.add(key)
        db.commit()
        print("Seeded E2E test API key (provider=openai)")


def _seed_epub_media(session_factory, user_id: UUID, settings) -> None:
    """Seed an EPUB with 3 chapters for EPUB reader E2E tests."""
    epub_bytes = _build_epub_bytes()
    filename = f"e2e-epub-seed-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}.epub"

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        init_data = init_upload(
            db=db,
            viewer_id=user_id,
            kind="epub",
            filename=filename,
            content_type="application/epub+zip",
            size_bytes=len(epub_bytes),
        )

    epub_media_id_str = init_data["media_id"]
    storage_path = init_data["storage_path"]
    token = init_data["token"]

    _upload_to_signed_url(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        bucket=settings.storage_bucket,
        storage_path=storage_path,
        token=token,
        content=epub_bytes,
        content_type="application/epub+zip",
    )

    with session_factory() as db:
        confirm_result = confirm_ingest(
            db=db,
            viewer_id=user_id,
            media_id=UUID(epub_media_id_str),
        )
    epub_media_id_str = confirm_result["media_id"]
    epub_media_id = UUID(epub_media_id_str)

    with session_factory() as db:
        extraction_result = run_epub_ingest_sync(db, epub_media_id)
        if isinstance(extraction_result, EpubExtractionError):
            raise RuntimeError(
                "Failed to seed EPUB artifacts: "
                f"{extraction_result.error_code} {extraction_result.error_message}"
            )

        media = db.execute(select(Media).where(Media.id == epub_media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Seeded EPUB media row disappeared: {epub_media_id_str}")

        now = datetime.now(UTC)
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_completed_at = now
        media.updated_at = now
        db.commit()

    _write_epub_seed_file(
        media_id=epub_media_id_str,
        chapter_count=len(EPUB_CHAPTERS),
        chapter_titles=[ch["title"] for ch in EPUB_CHAPTERS],
        toc_anchor_label=EPUB_TOC_ANCHOR_LABEL,
        toc_anchor_target_id=EPUB_TOC_ANCHOR_ID,
        toc_anchor_heading=EPUB_TOC_ANCHOR_HEADING,
    )
    print(f"Seeded EPUB media for E2E: {epub_media_id_str}")


def _seed_reader_resume_media(session_factory, user_id: UUID, settings) -> None:
    """Seed dedicated web/epub/pdf media for reader resume E2E coverage."""
    # ------------------------------------------------------------------
    # Web article (long canonical text with deterministic anchor token)
    # ------------------------------------------------------------------
    web_lines: list[str] = []
    for idx in range(1, 261):
        if idx == 190:
            web_lines.append(
                f"reader resume paragraph {idx:03d} contains {READER_RESUME_WEB_ANCHOR_TEXT} for anchor restore checks."
            )
        else:
            web_lines.append(
                f"reader resume paragraph {idx:03d} deterministic filler content for scroll-anchor persistence."
            )
    web_canonical_text = "\n".join(web_lines)
    web_html = "".join(f"<p>{escape(line)}</p>" for line in web_lines)

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        provisional = create_provisional_web_article(
            db=db,
            viewer_id=user_id,
            url=READER_RESUME_WEB_SOURCE_URL,
            enqueue_task=False,
        )
        web_media_id = provisional.media_id

    with session_factory() as db:
        media = db.execute(select(Media).where(Media.id == web_media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Reader-resume web media missing: {web_media_id}")

        _clear_fragment_artifacts(db, web_media_id)

        now = datetime.now(UTC)
        media.title = "E2E reader resume web seed"
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_started_at = now
        media.processing_completed_at = now
        media.updated_at = now

        db.add(
            Fragment(
                media_id=web_media_id,
                idx=0,
                canonical_text=web_canonical_text,
                html_sanitized=web_html,
            )
        )
        db.commit()

    # ------------------------------------------------------------------
    # EPUB (separate media id from primary EPUB seed to avoid state races)
    # ------------------------------------------------------------------
    epub_bytes = _build_epub_bytes("reader-resume")
    epub_filename = f"e2e-reader-resume-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}.epub"

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        epub_init = init_upload(
            db=db,
            viewer_id=user_id,
            kind="epub",
            filename=epub_filename,
            content_type="application/epub+zip",
            size_bytes=len(epub_bytes),
        )

    epub_media_id_str = epub_init["media_id"]
    _upload_to_signed_url(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        bucket=settings.storage_bucket,
        storage_path=epub_init["storage_path"],
        token=epub_init["token"],
        content=epub_bytes,
        content_type="application/epub+zip",
    )

    with session_factory() as db:
        confirm_result = confirm_ingest(
            db=db,
            viewer_id=user_id,
            media_id=UUID(epub_media_id_str),
        )
    epub_media_id_str = confirm_result["media_id"]
    epub_media_id = UUID(epub_media_id_str)
    with session_factory() as db:
        extraction_result = run_epub_ingest_sync(db, epub_media_id)
        if isinstance(extraction_result, EpubExtractionError):
            raise RuntimeError(
                "Failed to seed reader-resume EPUB artifacts: "
                f"{extraction_result.error_code} {extraction_result.error_message}"
            )

        media = db.execute(select(Media).where(Media.id == epub_media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Reader-resume EPUB media missing: {epub_media_id_str}")

        now = datetime.now(UTC)
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_completed_at = now
        media.updated_at = now
        db.commit()

    # ------------------------------------------------------------------
    # PDF (separate media id from primary PDF seed to avoid state races)
    # ------------------------------------------------------------------
    resume_pdf_bytes = _build_pdf_bytes(READER_RESUME_PDF_PAGE_COUNT)
    resume_pdf_filename = f"e2e-reader-resume-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}.pdf"

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        pdf_init = init_upload(
            db=db,
            viewer_id=user_id,
            kind="pdf",
            filename=resume_pdf_filename,
            content_type="application/pdf",
            size_bytes=len(resume_pdf_bytes),
        )

    pdf_media_id_str = pdf_init["media_id"]
    _upload_to_signed_url(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        bucket=settings.storage_bucket,
        storage_path=pdf_init["storage_path"],
        token=pdf_init["token"],
        content=resume_pdf_bytes,
    )

    with session_factory() as db:
        confirm_result = confirm_ingest(
            db=db,
            viewer_id=user_id,
            media_id=UUID(pdf_media_id_str),
        )
    pdf_media_id_str = confirm_result["media_id"]
    pdf_media_id = UUID(pdf_media_id_str)
    with session_factory() as db:
        extraction_result = run_pdf_ingest_sync(db, pdf_media_id)
        if isinstance(extraction_result, PdfExtractionError):
            raise RuntimeError(
                "Failed to seed reader-resume PDF artifacts: "
                f"{extraction_result.error_code} {extraction_result.error_message}"
            )

        media = db.execute(select(Media).where(Media.id == pdf_media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Reader-resume PDF media missing: {pdf_media_id_str}")

        now = datetime.now(UTC)
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_completed_at = now
        media.updated_at = now
        db.commit()

    _write_reader_resume_seed_file(
        web_media_id=str(web_media_id),
        web_anchor_text=READER_RESUME_WEB_ANCHOR_TEXT,
        epub_media_id=epub_media_id_str,
        epub_chapter_titles=[chapter["title"] for chapter in EPUB_CHAPTERS],
        pdf_media_id=pdf_media_id_str,
        pdf_page_count=READER_RESUME_PDF_PAGE_COUNT,
    )
    print(f"Seeded reader-resume web media for E2E: {web_media_id}")
    print(f"Seeded reader-resume EPUB media for E2E: {epub_media_id_str}")
    print(f"Seeded reader-resume PDF media for E2E: {pdf_media_id_str}")


def main() -> None:
    nexus_env = os.getenv("NEXUS_ENV", "local")
    if nexus_env not in ("local", "test"):
        print(f"ERROR: seed_e2e_data.py refuses to run in NEXUS_ENV={nexus_env}")
        sys.exit(1)

    if not os.getenv("DATABASE_URL"):
        print("ERROR: DATABASE_URL must be set")
        sys.exit(1)

    settings = get_settings()
    if not settings.supabase_url or not settings.supabase_service_key:
        print("ERROR: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set")
        sys.exit(1)

    user_id = _fetch_e2e_user_id(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        email=E2E_USER_EMAIL,
    )

    pdf_bytes = _build_pdf_bytes(PDF_PAGE_COUNT)
    session_factory = create_session_factory()
    filename = f"e2e-pdf-expiry-seed-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}.pdf"
    upload_fixture_path = _write_upload_fixture(pdf_bytes)

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        init_data = init_upload(
            db=db,
            viewer_id=user_id,
            kind="pdf",
            filename=filename,
            content_type="application/pdf",
            size_bytes=len(pdf_bytes),
        )

    uploaded_media_id_str = init_data["media_id"]
    storage_path = init_data["storage_path"]
    token = init_data["token"]

    _upload_to_signed_url(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        bucket=settings.storage_bucket,
        storage_path=storage_path,
        token=token,
        content=pdf_bytes,
    )

    with session_factory() as db:
        confirm_result = confirm_ingest(
            db=db, viewer_id=user_id, media_id=UUID(uploaded_media_id_str)
        )

    media_id_str = confirm_result["media_id"]
    media_id = UUID(media_id_str)

    with session_factory() as db:
        extraction_result = run_pdf_ingest_sync(db, media_id)
        if isinstance(extraction_result, PdfExtractionError):
            raise RuntimeError(
                "Failed to seed quote-ready PDF artifacts: "
                f"{extraction_result.error_code} {extraction_result.error_message}"
            )

        media = db.execute(select(Media).where(Media.id == media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Seeded media row disappeared before finalize: {media_id_str}")

        now = datetime.now(UTC)
        media.processing_status = ProcessingStatus.ready_for_reading
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_completed_at = now
        media.updated_at = now
        db.commit()

    password_filename = f"e2e-password-seed-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}.pdf"
    with session_factory() as db:
        password_init = init_upload(
            db=db,
            viewer_id=user_id,
            kind="pdf",
            filename=password_filename,
            content_type="application/pdf",
            size_bytes=1024,
        )
        password_media_id = UUID(password_init["media_id"])
        password_media = db.execute(
            select(Media).where(Media.id == password_media_id)
        ).scalar_one_or_none()
        if password_media is None:
            raise RuntimeError(f"Password-seed media missing: {password_media_id}")

        now = datetime.now(UTC)
        password_media.processing_status = ProcessingStatus.failed
        password_media.failure_stage = FailureStage.extract
        password_media.last_error_code = "E_PDF_PASSWORD_REQUIRED"
        password_media.last_error_message = "PDF is password-protected or encrypted"
        password_media.failed_at = now
        password_media.processing_completed_at = now
        password_media.updated_at = now
        db.commit()

    with session_factory() as db:
        media = db.execute(select(Media).where(Media.id == media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Seeded media row disappeared: {media_id_str}")
        page_count = media.page_count or PDF_PAGE_COUNT

    _write_seed_file(
        media_id=media_id_str,
        title=filename,
        page_count=page_count,
        upload_fixture_path=upload_fixture_path,
        password_media_id=str(password_media_id),
    )
    print(f"Seeded quote-ready PDF media for E2E: {media_id_str}")

    _seed_non_pdf_linked_items_media(session_factory, user_id)
    _seed_youtube_transcript_media(session_factory, user_id)
    _seed_api_key(session_factory, user_id)
    _seed_epub_media(session_factory, user_id, settings)
    _seed_reader_resume_media(session_factory, user_id, settings)


if __name__ == "__main__":
    main()
