#!/usr/bin/env python
"""Seed one readable PDF media row for zero-mock E2E tests.

This script:
1) Ensures the E2E user exists (created by e2e/seed-e2e-user.ts).
2) Bootstraps the app user + default library in Nexus DB.
3) Creates a PDF upload stub through the real upload service.
4) Uploads a generated multi-page PDF bytes payload to Supabase Storage.
5) Marks the media as ready_for_reading for deterministic reader tests.
6) Writes seeded media metadata to e2e/.seed/pdf-media.json.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path
from uuid import UUID

import fitz
import httpx
from sqlalchemy import select

from nexus.config import get_settings
from nexus.db.models import Media, ProcessingStatus
from nexus.db.session import create_session_factory
from nexus.services.bootstrap import ensure_user_and_default_library
from nexus.services.upload import init_upload

E2E_USER_EMAIL = os.getenv("E2E_USER_EMAIL", "e2e-test@nexus.local")
PDF_PAGE_COUNT = 80
SEED_FILE_RELATIVE = Path("e2e/.seed/pdf-media.json")


def _build_pdf_bytes(page_count: int) -> bytes:
    """Generate a simple multi-page PDF suitable for PDF.js rendering."""
    doc = fitz.open()
    for page_idx in range(page_count):
        page = doc.new_page()
        page.insert_text(
            (72, 72),
            f"E2E PDF signed-url expiry seed\nPage {page_idx + 1} of {page_count}",
            fontsize=14,
        )
        page.insert_text(
            (72, 120),
            "This file is generated by python/scripts/seed_e2e_pdf.py",
            fontsize=11,
        )
    try:
        return doc.tobytes()
    finally:
        doc.close()


def _fetch_e2e_user_id(supabase_url: str, service_key: str, email: str) -> UUID:
    """Lookup E2E auth user ID via Supabase admin API."""
    url = f"{supabase_url.rstrip('/')}/auth/v1/admin/users"
    headers = {
        "Authorization": f"Bearer {service_key}",
        "apikey": service_key,
    }
    with httpx.Client() as client:
        response = client.get(url, headers=headers, timeout=30.0)
    if response.status_code != 200:
        raise RuntimeError(f"Failed to list auth users: {response.status_code} {response.text}")

    payload = response.json()
    users = payload.get("users", [])
    for user in users:
        if user.get("email") == email:
            return UUID(user["id"])

    raise RuntimeError(f"E2E auth user not found for {email}. Run e2e/seed-e2e-user.ts first.")


def _upload_to_signed_url(
    *,
    supabase_url: str,
    service_key: str,
    bucket: str,
    storage_path: str,
    token: str,
    content: bytes,
) -> None:
    """Upload bytes through Supabase signed-upload endpoint."""
    url = f"{supabase_url.rstrip('/')}/storage/v1/object/upload/sign/{bucket}/{storage_path}"
    headers = {
        "Authorization": f"Bearer {service_key}",
        "apikey": service_key,
        "Content-Type": "application/pdf",
        "x-upsert": "false",
    }
    with httpx.Client() as client:
        response = client.put(
            url,
            params={"token": token},
            headers=headers,
            content=content,
            timeout=60.0,
        )

    if response.status_code not in (200, 201):
        raise RuntimeError(
            f"Failed to upload seeded PDF via signed URL: {response.status_code} {response.text}"
        )


def _write_seed_file(media_id: str, title: str, page_count: int) -> None:
    """Persist seeded media metadata for Playwright tests."""
    repo_root = Path(__file__).resolve().parents[2]
    seed_path = repo_root / SEED_FILE_RELATIVE
    seed_path.parent.mkdir(parents=True, exist_ok=True)
    seed_payload = {
        "media_id": media_id,
        "title": title,
        "page_count": page_count,
        "seeded_at": datetime.now(UTC).isoformat(),
    }
    seed_path.write_text(json.dumps(seed_payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote E2E PDF seed metadata: {seed_path}")


def main() -> None:
    nexus_env = os.getenv("NEXUS_ENV", "local")
    if nexus_env not in ("local", "test"):
        print(f"ERROR: seed_e2e_pdf.py refuses to run in NEXUS_ENV={nexus_env}")
        sys.exit(1)

    if not os.getenv("DATABASE_URL"):
        print("ERROR: DATABASE_URL must be set")
        sys.exit(1)

    settings = get_settings()
    if not settings.supabase_url or not settings.supabase_service_key:
        print("ERROR: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set")
        sys.exit(1)

    user_id = _fetch_e2e_user_id(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        email=E2E_USER_EMAIL,
    )

    pdf_bytes = _build_pdf_bytes(PDF_PAGE_COUNT)
    session_factory = create_session_factory()
    filename = f"e2e-pdf-expiry-seed-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}.pdf"

    with session_factory() as db:
        ensure_user_and_default_library(db, user_id)
        init_data = init_upload(
            db=db,
            viewer_id=user_id,
            kind="pdf",
            filename=filename,
            content_type="application/pdf",
            size_bytes=len(pdf_bytes),
        )

    media_id_str = init_data["media_id"]
    storage_path = init_data["storage_path"]
    token = init_data["token"]

    _upload_to_signed_url(
        supabase_url=settings.supabase_url,
        service_key=settings.supabase_service_key,
        bucket=settings.storage_bucket,
        storage_path=storage_path,
        token=token,
        content=pdf_bytes,
    )

    media_id = UUID(media_id_str)
    with session_factory() as db:
        media = db.execute(select(Media).where(Media.id == media_id)).scalar_one_or_none()
        if media is None:
            raise RuntimeError(f"Seeded media row disappeared: {media_id_str}")

        now = datetime.now(UTC)
        media.processing_status = ProcessingStatus.ready_for_reading
        media.page_count = PDF_PAGE_COUNT
        media.failure_stage = None
        media.last_error_code = None
        media.last_error_message = None
        media.failed_at = None
        media.processing_completed_at = now
        media.updated_at = now
        db.commit()

    _write_seed_file(media_id=media_id_str, title=filename, page_count=PDF_PAGE_COUNT)
    print(f"Seeded readable PDF media for E2E: {media_id_str}")


if __name__ == "__main__":
    main()
