#!/usr/bin/env bash
# Publish the production backend configuration to the host, content-addressed.
#
#   deploy/hetzner/sync-env.sh
#
# Writes /etc/nexus/config/<sha256>.env and /etc/nexus/backup-config/<sha256>.env
# and repoints /etc/nexus/current.env and /etc/nexus/backup.env at them with an
# atomic rename. The next release picks them up; nothing restarts here.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
readonly ROOT_DIR
readonly SSH_TARGET="nexus@5.78.194.235"
readonly -a SSH_OPTIONS=(-o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=15)

SHARED_ENV="${NEXUS_SHARED_ENV:-${ROOT_DIR}/deploy/env/env-prod}"
BACKEND_ENV="${NEXUS_BACKEND_ENV:-${ROOT_DIR}/deploy/env/env-prod-backend}"
WORKER_ENV="${NEXUS_WORKER_ENV:-${ROOT_DIR}/deploy/env/env-prod-worker}"
BACKUP_ENV="${NEXUS_BACKUP_ENV:-${ROOT_DIR}/deploy/env/env-prod-backup}"

# The keys the running backend requires. Compose fails closed on the few it
# interpolates itself (POSTGRES_*, CADDY_*); the rest are read by the app.
readonly REQUIRED_KEYS="
NEXUS_ENV APP_PUBLIC_URL SUPABASE_ISSUER SUPABASE_JWKS_URL SUPABASE_AUDIENCES
NEXUS_INTERNAL_SECRET STREAM_CORS_ORIGINS CADDY_SITE CADDY_ACME_EMAIL DATABASE_URL
POSTGRES_USER POSTGRES_DB POSTGRES_PASSWORD R2_S3_API_ORIGIN R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY R2_BUCKET STREAM_TOKEN_SIGNING_KEY STREAM_BASE_URL
NEXUS_ORACLE_CORPUS_OWNER_USER_ID BILLING_ENABLED PODCASTS_ENABLED
YOUTUBE_DATA_API_KEY X_API_BEARER_TOKEN OPENAI_API_KEY AGENT_TOOL_GRANT_SIGNING_KEY
GENERATION_API_PROVIDERS GENERATION_CONTINUATION_ENCRYPTION_KEY POSTGRES_IMAGE
CADDY_IMAGE PARSER_TEMP_ROOT
"
readonly BACKUP_KEYS="
R2_BACKUP_S3_API_ORIGIN R2_BACKUP_BUCKET R2_BACKUP_ACCESS_KEY_ID R2_BACKUP_SECRET_ACCESS_KEY
"

die() {
  echo "error: $*" >&2
  exit 1
}

value_of() {
  sed -n "s/^$1=//p" "$2" | tail -n1 | sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"
}

require_shape() {
  local file="$1" label="$2" key value
  awk '
    /^[[:space:]]*(#|$)/ { next }
    index($0, "=") == 0 { exit 2 }
    { key = substr($0, 1, index($0, "=") - 1)
      if (key !~ /^[A-Z][A-Z0-9_]*$/ || seen[key]++) { exit 3 } }
  ' "$file" || die "${label} must hold only valid, unique, unquoted-key assignments"
  grep -Ev '^[[:space:]]*#' "$file" | grep -Eq '[<>]|example\.com|=[Cc][Hh][Aa][Nn][Gg][Ee][Mm][Ee]$' && \
    die "${label} still contains placeholder values"
  for key in $3; do
    value="$(value_of "$key" "$file")"
    [ -n "$value" ] || die "${label} is missing a non-empty ${key}"
  done
}

publish() {
  local file="$1" directory="$2" pointer="$3" digest staged
  digest="$(sha256sum "$file" | cut -d' ' -f1)"
  staged="${REMOTE_DIRECTORY}/${digest}.env"
  timeout --foreground 2m scp "${SSH_OPTIONS[@]}" "$file" "${SSH_TARGET}:${staged}"
  timeout --foreground 1m ssh "${SSH_OPTIONS[@]}" "$SSH_TARGET" \
    "sudo install -D -o root -g root -m 0440 ${staged} ${directory}/${digest}.env \
     && sudo ln -sfn ${directory}/${digest}.env ${pointer}.staged \
     && sudo mv -T ${pointer}.staged ${pointer}"
  printf '%s -> %s/%s.env\n' "$pointer" "$directory" "$digest"
}

[ "$#" = 0 ] || die "usage: deploy/hetzner/sync-env.sh"
for command in scp sha256sum ssh timeout; do
  command -v "$command" >/dev/null 2>&1 || die "$command is not installed"
done
for file in "$SHARED_ENV" "$BACKEND_ENV" "$WORKER_ENV" "$BACKUP_ENV"; do
  [ -f "$file" ] || die "missing env file: $file"
done

TEMPORARY="$(mktemp -d)"
readonly TEMPORARY
REMOTE_DIRECTORY=""
cleanup() {
  rm -r -- "$TEMPORARY"
  if [[ "$REMOTE_DIRECTORY" =~ ^/tmp/nexus-config\.[A-Za-z0-9]{8}$ ]]; then
    timeout --foreground 30s ssh "${SSH_OPTIONS[@]}" "$SSH_TARGET" \
      rm -r -- "$REMOTE_DIRECTORY" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

readonly APPLICATION="${TEMPORARY}/application.env"
{
  echo "# Generated by deploy/hetzner/sync-env.sh"
  cat "$SHARED_ENV"
  echo
  cat "$BACKEND_ENV"
  echo
  cat "$WORKER_ENV"
} >"$APPLICATION"

require_shape "$APPLICATION" "the application env" "$REQUIRED_KEYS"
require_shape "$BACKUP_ENV" "the backup env" "$BACKUP_KEYS"
for key in $BACKUP_KEYS; do
  grep -Eq "^${key}=" "$APPLICATION" && \
    die "backup credentials must not enter the application config"
done
for key in POSTGRES_IMAGE CADDY_IMAGE; do
  [[ "$(value_of "$key" "$APPLICATION")" =~ ^[^[:space:]@]+@sha256:[0-9a-f]{64}$ ]] || \
    die "${key} must be an immutable image reference by sha256 digest"
done
[[ "$(value_of DATABASE_URL "$APPLICATION")" == *"@postgres:5432/"* ]] || \
  die "DATABASE_URL must address the Compose-local postgres service"
[[ "$(value_of R2_BACKUP_S3_API_ORIGIN "$BACKUP_ENV")" =~ ^https://[0-9a-f]{32}\.r2\.cloudflarestorage\.com$ ]] || \
  die "R2_BACKUP_S3_API_ORIGIN must be the account's R2 S3 API origin"

REMOTE_DIRECTORY="$(
  timeout --foreground 30s ssh "${SSH_OPTIONS[@]}" "$SSH_TARGET" \
    mktemp -d /tmp/nexus-config.XXXXXXXX
)"
[[ "$REMOTE_DIRECTORY" =~ ^/tmp/nexus-config\.[A-Za-z0-9]{8}$ ]] || \
  die "the host returned an invalid config transfer path"
publish "$APPLICATION" /etc/nexus/config /etc/nexus/current.env
publish "$BACKUP_ENV" /etc/nexus/backup-config /etc/nexus/backup.env
