#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

HOST="${NEXUS_HOST:-}"
DEPLOY_USER="${NEXUS_DEPLOY_USER:-nexus}"
ENV_TARGET="${NEXUS_REMOTE_ENV_FILE:-/etc/nexus/nexus.env}"
SSH_TARGET="${NEXUS_SSH_TARGET:-${DEPLOY_USER}@${HOST}}"

SHARED_ENV="${NEXUS_SHARED_ENV:-${ROOT_DIR}/deploy/env/env-prod}"
BACKEND_ENV="${NEXUS_BACKEND_ENV:-${ROOT_DIR}/deploy/env/env-prod-backend}"
WORKER_ENV="${NEXUS_WORKER_ENV:-${ROOT_DIR}/deploy/env/env-prod-worker}"

die() {
  echo "error: $*" >&2
  exit 1
}

[ -n "$HOST" ] || [ -n "${NEXUS_SSH_TARGET:-}" ] || die "set NEXUS_HOST or NEXUS_SSH_TARGET"
command -v ssh >/dev/null 2>&1 || die "ssh is not installed locally"
command -v scp >/dev/null 2>&1 || die "scp is not installed locally"

for file in "$SHARED_ENV" "$BACKEND_ENV" "$WORKER_ENV"; do
  [ -f "$file" ] || die "missing env file: $file"
done

tmp_file="$(mktemp)"
remote_tmp="/tmp/nexus.env.$$"
trap 'rm -f "$tmp_file"' EXIT

{
  echo "# Generated by deploy/hetzner/sync-env.sh"
  echo "# Source files:"
  echo "# - ${SHARED_ENV#$ROOT_DIR/}"
  echo "# - ${BACKEND_ENV#$ROOT_DIR/}"
  echo "# - ${WORKER_ENV#$ROOT_DIR/}"
  echo
  cat "$SHARED_ENV"
  echo
  cat "$BACKEND_ENV"
  echo
  cat "$WORKER_ENV"
} >"$tmp_file"

if grep -Ev '^[[:space:]]*#' "$tmp_file" | grep -Eq '[<>]|example\.com|=changeme$|=CHANGEME$'; then
  die "env files still contain placeholder values"
fi

scp "$tmp_file" "${SSH_TARGET}:${remote_tmp}"
ssh "$SSH_TARGET" "sudo install -d -o root -g ${DEPLOY_USER} -m 0750 /etc/nexus && sudo install -o root -g ${DEPLOY_USER} -m 0640 '${remote_tmp}' '${ENV_TARGET}' && rm -f '${remote_tmp}'"

echo "uploaded ${ENV_TARGET}"
