// @generated by python/scripts/generate_tool_contract_projection.py from
// BROWSER_TOOL_PROJECTION_CONTRACT in
// python/nexus/services/tool_runtime/declarations.py. Run the owning generator;
// do not edit this file by hand.

export const TOOL_CONTRACT_PROJECTION = {"effects":["Pure","Read","Write"],"error_types":["BudgetExceeded","Conflict","DeadlineExceeded","InvalidInput","InvalidUpstreamResponse","InvalidUrl","QuoteAmbiguous","QuoteNotFound","RateLimited","ResourceUnavailable","TargetAmbiguous","TooLarge","ToolUnavailable","Uninspectable","Unreadable","UnsafeDestination","UnsupportedContent","UpstreamUnavailable","WriteCapReached"],"fields":["activity_label","canonical_tool_id","effect","error_type","provider_wire_name","record_kind","result_kind"],"record_kinds":["attached_context","current_execution","historical_execution","rejected_provider_call"],"record_shapes":{"attached_context":{"non_null_fields":["activity_label","record_kind","result_kind"],"null_fields":["canonical_tool_id","effect","error_type","provider_wire_name"]},"current_execution":{"non_null_fields":["activity_label","canonical_tool_id","effect","record_kind","result_kind"],"null_fields":[]},"historical_execution":{"non_null_fields":["activity_label","canonical_tool_id","effect","record_kind","result_kind"],"null_fields":["error_type","provider_wire_name"]},"rejected_provider_call":{"non_null_fields":["activity_label","provider_wire_name","record_kind","result_kind"],"null_fields":["canonical_tool_id","effect","error_type"]}},"result_kinds":["attached_context","mutation","navigation","rejected_provider_call","retrieval"]} as const;

export const TOOL_PROJECTION_REVISION = "e62160b48374ba9853305a5121a7163f8134b93b3cc2ab7d0270a0add704fc24" as const;

export type ToolProjectionField =
  (typeof TOOL_CONTRACT_PROJECTION.fields)[number];
export type ToolEffect = (typeof TOOL_CONTRACT_PROJECTION.effects)[number];
export type ToolResultKind =
  (typeof TOOL_CONTRACT_PROJECTION.result_kinds)[number];
export type ToolErrorType =
  (typeof TOOL_CONTRACT_PROJECTION.error_types)[number];
export type ToolRecordKind =
  (typeof TOOL_CONTRACT_PROJECTION.record_kinds)[number];
