// @generated by python/scripts/generate_tool_contract_projection.py from
// BROWSER_TOOL_PROJECTION_CONTRACT in
// python/nexus/services/tool_runtime/declarations.py. Run the owning generator;
// do not edit this file by hand.

export const TOOL_CONTRACT_PROJECTION = {"effects":["Pure","Read","Write"],"error_types":["BudgetExceeded","Conflict","DeadlineExceeded","InvalidInput","InvalidUpstreamResponse","InvalidUrl","QuoteAmbiguous","QuoteNotFound","RateLimited","ResourceUnavailable","TargetAmbiguous","TooLarge","ToolUnavailable","Uninspectable","Unreadable","UnsafeDestination","UnsupportedContent","UpstreamUnavailable","WriteCapReached"],"fields":["activity_label","canonical_tool_id","effect","error_type","provider_wire_name","record_kind","result_kind"],"record_kinds":["attached_context","current_execution","historical_execution"],"result_kinds":["attached_context","mutation","navigation","retrieval"]} as const;

export const TOOL_PROJECTION_REVISION = "e10e7ed27bd88c6c9f6fd0daa7e5c29d58ebe9cb8251b4ba8956ca812580d4c6" as const;

export type ToolProjectionField =
  (typeof TOOL_CONTRACT_PROJECTION.fields)[number];
export type ToolEffect = (typeof TOOL_CONTRACT_PROJECTION.effects)[number];
export type ToolResultKind =
  (typeof TOOL_CONTRACT_PROJECTION.result_kinds)[number];
export type ToolErrorType =
  (typeof TOOL_CONTRACT_PROJECTION.error_types)[number];
export type ToolRecordKind =
  (typeof TOOL_CONTRACT_PROJECTION.record_kinds)[number];
