"use client";

export const OVERVIEW_RULER_WIDTH_PX = 28;
export const SECONDARY_RAIL_EXPANDED_WIDTH_PX = 360;
export const SECONDARY_RAIL_COLLAPSED_WIDTH_PX = 36;
export const CONVERSATION_REFERENCES_RAIL_WIDTH_PX = 320;
