// Auto-generated by scripts/build-icons.mjs from apps/web/public/brand/asterism.svg.
// Run `make build-icons` to regenerate. Do not edit by hand.

export const ASTERISM_VIEWBOX = 64;

export const ASTERISM_DOTS = [
  { cx: 32, cy: 22, r: 8.5 },
  { cx: 22, cy: 40, r: 8.5 },
  { cx: 42, cy: 40, r: 8.5 },
] as const;

export const BRAND_FG_ON_DARK = "#c4a472";
export const BRAND_FG_ON_LIGHT = "#7d5e35";
export const BRAND_BG_DARK = "#15140f";
